// Code generated by gsbmcodegen. DO NOT EDIT.

package aliasptr

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Batch) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Items
	w.WriteTag(1, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			inner := w.BeginLengthDelim()
			if v.Items[i] == nil {
				w.WritePresenceNil()
			} else {
				w.WritePresenceNonZero()
				if err := v.Items[i].MarshalGSBM(w); err != nil {
					return err
				}
			}
			w.EndLengthDelim(inner)
		}
		w.EndLengthDelim(m)
	}
	// tag 2 Optional
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Optional)))
		for i := range v.Optional {
			inner := w.BeginLengthDelim()
			if v.Optional[i] == nil {
				w.WritePresenceNil()
			} else {
				w.WritePresenceNonZero()
				if err := v.Optional[i].MarshalGSBM(w); err != nil {
					return err
				}
			}
			w.EndLengthDelim(inner)
		}
		w.EndLengthDelim(m)
	}
	// tag 3 Groups
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Groups)))
		for i := range v.Groups {
			inner := w.BeginLengthDelim()
			if err := v.Groups[i].MarshalGSBM(w); err != nil {
				return err
			}
			w.EndLengthDelim(inner)
		}
		w.EndLengthDelim(m)
	}
	// tag 4 OptionalGroups
	w.WriteTag(4, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.OptionalGroups)))
		for i := range v.OptionalGroups {
			inner := w.BeginLengthDelim()
			if v.OptionalGroups[i] == nil {
				w.WritePresenceNil()
			} else {
				w.WritePresenceNonZero()
				if err := v.OptionalGroups[i].MarshalGSBM(w); err != nil {
					return err
				}
			}
			w.EndLengthDelim(inner)
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Batch) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Items) >= n {
					v.Items = v.Items[:n]
				} else {
					v.Items = gsbm.MakeSlice[*Item](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				state, err := r.ReadPresenceByte(false)
				if err != nil {
					return err
				}
				switch state {
				case gsbm.PresenceNil:
					v.Items[i] = nil
				case gsbm.PresenceNonZero:
					if v.Items[i] == nil {
						v.Items[i] = &Item{}
					} else {
						v.Items[i].Reset()
					}
					if err := v.Items[i].UnmarshalGSBM(r); err != nil {
						return err
					}
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Optional) >= n {
					v.Optional = v.Optional[:n]
				} else {
					v.Optional = gsbm.MakeSlice[*OptionalNote](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				state, err := r.ReadPresenceByte(false)
				if err != nil {
					return err
				}
				switch state {
				case gsbm.PresenceNil:
					v.Optional[i] = nil
				case gsbm.PresenceNonZero:
					if v.Optional[i] == nil {
						v.Optional[i] = &OptionalNote{}
					} else {
						v.Optional[i].Reset()
					}
					if err := v.Optional[i].UnmarshalGSBM(r); err != nil {
						return err
					}
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 2)
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Groups) >= n {
					v.Groups = v.Groups[:n]
				} else {
					v.Groups = gsbm.MakeSlice[Item](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.Groups[i].Reset()
				if err := v.Groups[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 3)
		case 4:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.OptionalGroups) >= n {
					v.OptionalGroups = v.OptionalGroups[:n]
				} else {
					v.OptionalGroups = gsbm.MakeSlice[*Item](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				state, err := r.ReadPresenceByte(false)
				if err != nil {
					return err
				}
				switch state {
				case gsbm.PresenceNil:
					v.OptionalGroups[i] = nil
				case gsbm.PresenceNonZero:
					if v.OptionalGroups[i] == nil {
						v.OptionalGroups[i] = &Item{}
					} else {
						v.OptionalGroups[i].Reset()
					}
					if err := v.OptionalGroups[i].UnmarshalGSBM(r); err != nil {
						return err
					}
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 4)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Batch) Reset() {
	v.Items = v.Items[:0]
	v.Optional = v.Optional[:0]
	for i := range v.Groups {
		v.Groups[i].Reset()
	}
	v.Groups = v.Groups[:0]
	v.OptionalGroups = v.OptionalGroups[:0]
	gsbm.ClearPresence(v)
}

func (v *Batch) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
