// Code generated by gsbmcodegen. DO NOT EDIT.

package aliasptr

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *OptionalNote) SizeGSBM() int {
	var n int
	// tag 1 Value
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Value)
	return n
}

func (v *OptionalNote) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Value
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Value)
	return w.Err()
}

func (v *OptionalNote) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Value = x
			}
			present[0] |= 1 << 0
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *OptionalNote) Reset() {
	v.Value = ""
	gsbm.ClearPresence(v)
}

func (v *OptionalNote) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
