// Code generated by gsbmcodegen. DO NOT EDIT.

package customcodec

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *AliasContainer) SizeGSBM() int {
	n := 0
	// tag 1 Pages
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Pages)))
		for i := range v.Pages {
			body_1 += gsbm.SizeLengthDelim(v.Pages[i].SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	return n
}

func (v *AliasContainer) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Pages
	w.WriteTag(1, gsbm.WireLengthDelim)
	{
		mOuter := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Pages)))
		for i := range v.Pages {
			mElem := w.BeginLengthDelim()
			if err := v.Pages[i].MarshalGSBM(w); err != nil {
				return err
			}
			w.EndLengthDelim(mElem)
		}
		w.EndLengthDelim(mOuter)
	}
	return w.Err()
}

func (v *AliasContainer) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Pages) >= n {
					v.Pages = v.Pages[:n]
				} else {
					v.Pages = gsbm.MakeSlice[Record](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.Pages[i].Reset()
				if err := v.Pages[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 0
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *AliasContainer) Reset() {
	for i := range v.Pages {
		v.Pages[i].Reset()
	}
	v.Pages = v.Pages[:0]
	gsbm.ClearPresence(v)
}

func (v *AliasContainer) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
