// Code generated by gsbmcodegen. DO NOT EDIT.

package customcodec

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"sort"
)

func (v *Container) SizeGSBM() int {
	n := 0
	// tag 1 Inner
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeLengthDelim(v.Inner.SizeGSBM())
	// tag 2 Items
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			body_1 += gsbm.SizeLengthDelim(v.Items[i].SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 3 ByKey
	n += gsbm.SizeTag(3, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.ByKey)))
		for k, vv := range v.ByKey {
			body_1 += gsbm.SizeString(k)
			body_1 += gsbm.SizeLengthDelim(vv.SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 4 PtrItems
	n += gsbm.SizeTag(4, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.PtrItems)))
		for i := range v.PtrItems {
			eb_1 := 1
			if v.PtrItems[i] != nil {
				eb_1 += v.PtrItems[i].SizeGSBM()
			}
			body_1 += gsbm.SizeLengthDelim(eb_1)
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 5 Pages
	n += gsbm.SizeTag(5, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Pages)))
		for i := range v.Pages {
			{
				body_2 := gsbm.SizeUvarint(uint64(len(v.Pages[i])))
				for i_1 := range v.Pages[i] {
					body_2 += gsbm.SizeLengthDelim(v.Pages[i][i_1].SizeGSBM())
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 6 Buckets
	n += gsbm.SizeTag(6, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Buckets)))
		for i := range v.Buckets {
			{
				body_2 := gsbm.SizeUvarint(uint64(len(v.Buckets[i])))
				for k_1, vv_1 := range v.Buckets[i] {
					body_2 += gsbm.SizeString(k_1)
					body_2 += gsbm.SizeLengthDelim(vv_1.SizeGSBM())
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 7 Aliased
	n += gsbm.SizeTag(7, gsbm.WireLengthDelim)
	n += gsbm.SizeLengthDelim(v.Aliased.SizeGSBM())
	return n
}

func (v *Container) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Inner
	w.WriteTag(1, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if err := v.Inner.MarshalGSBM(w); err != nil {
			return err
		}
		w.EndLengthDelim(m)
	}
	// tag 2 Items
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		mOuter := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			mElem := w.BeginLengthDelim()
			if err := v.Items[i].MarshalGSBM(w); err != nil {
				return err
			}
			w.EndLengthDelim(mElem)
		}
		w.EndLengthDelim(mOuter)
	}
	// tag 3 ByKey
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		mOuter := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.ByKey)))
		keys := make([]string, 0, len(v.ByKey))
		for k := range v.ByKey {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.ByKey[k]
			w.WriteString(k)
			{
				m := w.BeginLengthDelim()
				if err := vv.MarshalGSBM(w); err != nil {
					return err
				}
				w.EndLengthDelim(m)
			}
		}
		w.EndLengthDelim(mOuter)
	}
	// tag 4 PtrItems
	w.WriteTag(4, gsbm.WireLengthDelim)
	{
		mOuter := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.PtrItems)))
		for i := range v.PtrItems {
			mElem := w.BeginLengthDelim()
			if v.PtrItems[i] == nil {
				w.WritePresenceNil()
			} else {
				w.WritePresenceNonZero()
				if err := v.PtrItems[i].MarshalGSBM(w); err != nil {
					return err
				}
			}
			w.EndLengthDelim(mElem)
		}
		w.EndLengthDelim(mOuter)
	}
	// tag 5 Pages
	w.WriteTag(5, gsbm.WireLengthDelim)
	{
		mOuter := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Pages)))
		for i := range v.Pages {
			{
				mOuter_1 := w.BeginLengthDelim()
				w.WriteUvarint(uint64(len(v.Pages[i])))
				for i_1 := range v.Pages[i] {
					mElem_1 := w.BeginLengthDelim()
					if err := v.Pages[i][i_1].MarshalGSBM(w); err != nil {
						return err
					}
					w.EndLengthDelim(mElem_1)
				}
				w.EndLengthDelim(mOuter_1)
			}
		}
		w.EndLengthDelim(mOuter)
	}
	// tag 6 Buckets
	w.WriteTag(6, gsbm.WireLengthDelim)
	{
		mOuter := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Buckets)))
		for i := range v.Buckets {
			{
				mOuter_1 := w.BeginLengthDelim()
				w.WriteUvarint(uint64(len(v.Buckets[i])))
				keys_1 := make([]string, 0, len(v.Buckets[i]))
				for k_1 := range v.Buckets[i] {
					keys_1 = append(keys_1, k_1)
				}
				sort.Strings(keys_1)
				for _, k_1 := range keys_1 {
					vv_1 := v.Buckets[i][k_1]
					w.WriteString(k_1)
					{
						m := w.BeginLengthDelim()
						if err := vv_1.MarshalGSBM(w); err != nil {
							return err
						}
						w.EndLengthDelim(m)
					}
				}
				w.EndLengthDelim(mOuter_1)
			}
		}
		w.EndLengthDelim(mOuter)
	}
	// tag 7 Aliased
	w.WriteTag(7, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if err := v.Aliased.MarshalGSBM(w); err != nil {
			return err
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Container) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			if err := v.Inner.UnmarshalGSBM(r); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Items) >= n {
					v.Items = v.Items[:n]
				} else {
					v.Items = gsbm.MakeSlice[Record](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.Items[i].Reset()
				if err := v.Items[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.ByKey == nil {
				v.ByKey = gsbm.MakeMap[string, Record](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv Record
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				if err := vv.UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
				v.ByKey[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 2
		case 4:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.PtrItems) >= n {
					v.PtrItems = v.PtrItems[:n]
				} else {
					v.PtrItems = gsbm.MakeSlice[*Record](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				state, err := r.ReadPresenceByte(false)
				if err != nil {
					return err
				}
				switch state {
				case gsbm.PresenceNil:
					v.PtrItems[i] = nil
				case gsbm.PresenceNonZero:
					if v.PtrItems[i] == nil {
						v.PtrItems[i] = &Record{}
					} else {
						v.PtrItems[i].Reset()
					}
					if err := v.PtrItems[i].UnmarshalGSBM(r); err != nil {
						return err
					}
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 3
		case 5:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Pages) >= n {
					v.Pages = v.Pages[:n]
				} else {
					v.Pages = gsbm.MakeSlice[[]Record](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				v.Pages[i] = v.Pages[i][:0]
				saved_1, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				n_1, err := r.ReadLength()
				if err != nil {
					return err
				}
				if n_1 > 0 {
					if cap(v.Pages[i]) >= n_1 {
						v.Pages[i] = v.Pages[i][:n_1]
					} else {
						v.Pages[i] = gsbm.MakeSlice[Record](r, n_1)
					}
					if err := r.Err(); err != nil {
						return err
					}
				}
				for i_1 := 0; i_1 < n_1; i_1++ {
					inner_1, err := r.BeginLengthDelim()
					if err != nil {
						return err
					}
					v.Pages[i][i_1].Reset()
					if err := v.Pages[i][i_1].UnmarshalGSBM(r); err != nil {
						return err
					}
					if err := r.EndLengthDelim(inner_1); err != nil {
						return err
					}
				}
				if err := r.EndLengthDelim(saved_1); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 4
		case 6:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Buckets) >= n {
					v.Buckets = v.Buckets[:n]
				} else {
					v.Buckets = gsbm.MakeSlice[map[string]Record](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				clear(v.Buckets[i])
				saved_1, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				n_1, err := r.ReadLength()
				if err != nil {
					return err
				}
				if n_1 > 0 && v.Buckets[i] == nil {
					v.Buckets[i] = gsbm.MakeMap[string, Record](r, n_1)
				}
				for i_1 := 0; i_1 < n_1; i_1++ {
					var k_1 string
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						k_1 = x
					}
					var vv_1 Record
					inner_1, err := r.BeginLengthDelim()
					if err != nil {
						return err
					}
					if err := vv_1.UnmarshalGSBM(r); err != nil {
						return err
					}
					if err := r.EndLengthDelim(inner_1); err != nil {
						return err
					}
					v.Buckets[i][k_1] = vv_1
				}
				if err := r.EndLengthDelim(saved_1); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 5
		case 7:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			if err := v.Aliased.UnmarshalGSBM(r); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 6
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Container) Reset() {
	v.Inner.Reset()
	for i := range v.Items {
		v.Items[i].Reset()
	}
	v.Items = v.Items[:0]
	clear(v.ByKey)
	clear(v.PtrItems)
	v.PtrItems = v.PtrItems[:0]
	clear(v.Pages)
	v.Pages = v.Pages[:0]
	clear(v.Buckets)
	v.Buckets = v.Buckets[:0]
	v.Aliased.Reset()
	gsbm.ClearPresence(v)
}

func (v *Container) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
