// Code generated by gsbmcodegen. DO NOT EDIT.

package customcodec

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"go.flaticols.dev/gsbm/tools/gsbmcodegen/codecs/builtins"
	"time"
)

const (
	csRecord_2 uint64 = 0x83a0df36a7404ec6
)

func (v *Record) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *Record) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 CreatedAt
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteUvarint(uint64(builtins.SizeTime(v.CreatedAt)))
	if err := builtins.EncodeTime(w, v.CreatedAt); err != nil {
		return err
	}
	// tag 2 Amount
	w.WriteTag(2, gsbm.WireLengthDelim)
	if err := EmitDecimalAmount(w, v.Amount, csRecord_2); err != nil {
		return err
	}
	// tag 3 OptionalAt
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if v.OptionalAt == nil {
			w.WritePresenceNil()
		} else {
			w.WritePresenceNonZero()
			if err := builtins.EncodeTime(w, *v.OptionalAt); err != nil {
				return err
			}
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Record) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			if err := builtins.DecodeTime(r, &v.CreatedAt); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			if err := DecodeDecimalAmount(r, &v.Amount); err != nil {
				return err
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(false)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.OptionalAt = nil
			case gsbm.PresenceNonZero:
				var tmp time.Time
				if err := builtins.DecodeTime(r, &tmp); err != nil {
					return err
				}
				v.OptionalAt = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 2
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Record) Reset() {
	v.CreatedAt = *new(time.Time)
	v.Amount = *new(DecimalAmount)
	v.OptionalAt = nil
	gsbm.ClearPresence(v)
}

func (v *Record) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
