// Code generated by gsbmcodegen. DO NOT EDIT.

package customcodec

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"go.flaticols.dev/gsbm/tools/gsbmcodegen/codecs/builtins"
	"time"
)

const (
	csRecord_2 uint64 = 0x83a0df36a7404ec6
	csRecord_4 uint64 = 0x83a0e136a740522c
)

func (v *Record) SizeGSBM() int {
	n := 0
	// tag 1 CreatedAt
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeLengthDelim(builtins.SizeTime(v.CreatedAt))
	// tag 2 Amount
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	{
		cw := gsbm.NewCountingWriter()
		_ = EmitDecimalAmount(cw, v.Amount, csRecord_2)
		n += cw.Size()
	}
	// tag 3 OptionalAt
	n += gsbm.SizeTag(3, gsbm.WireLengthDelim)
	{
		body := 1
		if v.OptionalAt != nil {
			body += gsbm.SizeLengthDelim(builtins.SizeTime(*v.OptionalAt))
		}
		n += gsbm.SizeLengthDelim(body)
	}
	// tag 4 AmountAppend
	n += gsbm.SizeTag(4, gsbm.WireLengthDelim)
	{
		cw := gsbm.NewCountingWriter()
		_ = EmitDecimalAmountAppend(cw, v.AmountAppend, csRecord_4)
		n += cw.Size()
	}
	// tag 5 Payload
	n += gsbm.SizeTag(5, gsbm.WireLengthDelim)
	{
		cw := gsbm.NewCountingWriter()
		_ = StreamLargePayload(cw, v.Payload)
		n += cw.Size()
	}
	// tag 6 AmountBinary
	n += gsbm.SizeTag(6, gsbm.WireLengthDelim)
	n += gsbm.SizeLengthDelim(SizeDecimalAmountBinary(v.AmountBinary))
	return n
}

func (v *Record) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 CreatedAt
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteUvarint(uint64(builtins.SizeTime(v.CreatedAt)))
	if err := builtins.EncodeTime(w, v.CreatedAt); err != nil {
		return err
	}
	// tag 2 Amount
	w.WriteTag(2, gsbm.WireLengthDelim)
	if err := EmitDecimalAmount(w, v.Amount, csRecord_2); err != nil {
		return err
	}
	// tag 3 OptionalAt
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if v.OptionalAt == nil {
			w.WritePresenceNil()
		} else {
			w.WritePresenceNonZero()
			w.WriteUvarint(uint64(builtins.SizeTime(*v.OptionalAt)))
			if err := builtins.EncodeTime(w, *v.OptionalAt); err != nil {
				return err
			}
		}
		w.EndLengthDelim(m)
	}
	// tag 4 AmountAppend
	w.WriteTag(4, gsbm.WireLengthDelim)
	if err := EmitDecimalAmountAppend(w, v.AmountAppend, csRecord_4); err != nil {
		return err
	}
	// tag 5 Payload
	w.WriteTag(5, gsbm.WireLengthDelim)
	if err := StreamLargePayload(w, v.Payload); err != nil {
		return err
	}
	// tag 6 AmountBinary
	w.WriteTag(6, gsbm.WireLengthDelim)
	w.WriteUvarint(uint64(SizeDecimalAmountBinary(v.AmountBinary)))
	if err := EncodeDecimalAmountBinary(w, v.AmountBinary); err != nil {
		return err
	}
	return w.Err()
}

func (v *Record) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			if err := builtins.DecodeTime(r, &v.CreatedAt); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			if err := DecodeDecimalAmount(r, &v.Amount); err != nil {
				return err
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(false)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.OptionalAt = nil
			case gsbm.PresenceNonZero:
				var tmp time.Time
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				if err := builtins.DecodeTime(r, &tmp); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
				v.OptionalAt = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 2
		case 4:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			if err := DecodeDecimalAmountAppend(r, &v.AmountAppend); err != nil {
				return err
			}
			present[0] |= 1 << 3
		case 5:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			if err := DecodeLargePayload(r, &v.Payload); err != nil {
				return err
			}
			present[0] |= 1 << 4
		case 6:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			if err := DecodeDecimalAmountBinary(r, &v.AmountBinary); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 5
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Record) Reset() {
	v.CreatedAt = *new(time.Time)
	v.Amount = *new(DecimalAmount)
	v.OptionalAt = nil
	v.AmountAppend = *new(DecimalAmount)
	v.Payload = *new(LargePayload)
	v.AmountBinary = *new(DecimalAmount)
	gsbm.ClearPresence(v)
}

func (v *Record) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
