// Code generated by gsbmcodegen. DO NOT EDIT.

package namedkey

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"math"
	"sort"
)

func (v *Counts) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *Counts) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ByCode
	w.WriteTag(1, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.ByCode)))
		keys := make([]Code, 0, len(v.ByCode))
		for k := range v.ByCode {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		for _, k := range keys {
			vv := v.ByCode[k]
			w.WriteString((string)(k))
			w.WriteVarint(int64(vv))
		}
		w.EndLengthDelim(m)
	}
	// tag 2 BySeverity
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.BySeverity)))
		keys := make([]Severity, 0, len(v.BySeverity))
		for k := range v.BySeverity {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		for _, k := range keys {
			vv := v.BySeverity[k]
			w.WriteVarint(int64((int8)(k)))
			w.WriteVarint(int64(vv))
		}
		w.EndLengthDelim(m)
	}
	// tag 3 ByBucket
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.ByBucket)))
		keys := make([]Bucket, 0, len(v.ByBucket))
		for k := range v.ByBucket {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		for _, k := range keys {
			vv := v.ByBucket[k]
			w.WriteUvarint(uint64((uint16)(k)))
			w.WriteVarint(int64(vv))
		}
		w.EndLengthDelim(m)
	}
	// tag 4 ByFlag
	w.WriteTag(4, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.ByFlag)))
		keys := make([]Flag, 0, len(v.ByFlag))
		for k := range v.ByFlag {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return !bool(keys[i]) && bool(keys[j]) })
		for _, k := range keys {
			vv := v.ByFlag[k]
			w.WriteBool((bool)(k))
			w.WriteVarint(int64(vv))
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Counts) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.ByCode == nil {
				v.ByCode = gsbm.MakeMap[Code, int64](r, n)
			}
			for i := 0; i < n; i++ {
				var k Code
				{
					var tmp string
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						tmp = x
					}
					k = Code(tmp)
				}
				var vv int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					vv = int64(x)
				}
				v.ByCode[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.BySeverity == nil {
				v.BySeverity = gsbm.MakeMap[Severity, int64](r, n)
			}
			for i := 0; i < n; i++ {
				var k Severity
				{
					var tmp int8
					{
						x, err := r.ReadVarint()
						if err != nil {
							return err
						}
						if x < math.MinInt8 || x > math.MaxInt8 {
							return gsbm.ErrIntegerOverflow
						}
						tmp = int8(x)
					}
					k = Severity(tmp)
				}
				var vv int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					vv = int64(x)
				}
				v.BySeverity[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.ByBucket == nil {
				v.ByBucket = gsbm.MakeMap[Bucket, int64](r, n)
			}
			for i := 0; i < n; i++ {
				var k Bucket
				{
					var tmp uint16
					{
						x, err := r.ReadUvarint()
						if err != nil {
							return err
						}
						if x > math.MaxUint16 {
							return gsbm.ErrIntegerOverflow
						}
						tmp = uint16(x)
					}
					k = Bucket(tmp)
				}
				var vv int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					vv = int64(x)
				}
				v.ByBucket[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 2
		case 4:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.ByFlag == nil {
				v.ByFlag = gsbm.MakeMap[Flag, int64](r, n)
			}
			for i := 0; i < n; i++ {
				var k Flag
				{
					var tmp bool
					{
						x, err := r.ReadBool()
						if err != nil {
							return err
						}
						tmp = x
					}
					k = Flag(tmp)
				}
				var vv int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					vv = int64(x)
				}
				v.ByFlag[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 3
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Counts) Reset() {
	clear(v.ByCode)
	clear(v.BySeverity)
	clear(v.ByBucket)
	clear(v.ByFlag)
	gsbm.ClearPresence(v)
}

func (v *Counts) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
