// Code generated by gsbmcodegen (arena mode). DO NOT EDIT.

package namedkey

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"go.flaticols.dev/gsbm/storage/gsbmarena"
)

// DecodeCounts decodes data into a *Counts allocated from a. The returned
// value, and every string/slice it transitively references, are
// invalidated by a.Release. The wire format is identical to heap mode.
func DecodeCounts(data []byte, a *gsbmarena.Arena) (*Counts, error) {
	v := gsbmarena.AllocStruct[Counts](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if _, _, err := r.ReadHeader(); err != nil {
		return nil, err
	}
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DecodeCountsBody is the headerless variant: data is the raw root body
// without the 8-byte blob header.
func DecodeCountsBody(data []byte, a *gsbmarena.Arena) (*Counts, error) {
	v := gsbmarena.AllocStruct[Counts](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DetachCounts returns a heap-allocated *Counts with no references into any
// arena. Implemented as a re-encode + heap decode round-trip so the
// heap-mode unmarshal body is the single source of truth.
func DetachCounts(o *Counts) (*Counts, error) {
	w := gsbm.NewWriter(nil)
	if err := o.MarshalGSBM(w); err != nil {
		return nil, err
	}
	if err := w.Err(); err != nil {
		return nil, err
	}
	dst := &Counts{}
	if err := gsbm.DecodeBodyInto(w.Bytes(), dst); err != nil {
		return nil, err
	}
	return dst, nil
}
