// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Branch) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Label
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Label)
	// tag 2 Leaf
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if err := v.Leaf.MarshalGSBM(w); err != nil {
			return err
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Branch) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Label = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			v.Leaf.Reset()
			if err := v.Leaf.UnmarshalGSBM(r); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 2)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Branch) Reset() {
	v.Label = ""
	v.Leaf.Reset()
	gsbm.ClearPresence(v)
}

func (v *Branch) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}

func (v *Branch) ForgetPresenceTree() {
	v.Leaf.ForgetPresenceTree()
	gsbm.ForgetPresence(v)
}

func (v *Branch) ForgetValuePresenceTree() {
	v.Leaf.ForgetValuePresenceTree()
	gsbm.ForgetPresence(v)
}
