// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Customer) SizeGSBM() int {
	n := 0
	// tag 1 Name
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Name)
	// tag 2 Email
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Email)
	return n
}

func (v *Customer) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Name
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Name)
	// tag 2 Email
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.Email)
	return w.Err()
}

func (v *Customer) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Name = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Email = x
			}
			present[0] |= 1 << 1
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Customer) Reset() {
	v.Name = ""
	v.Email = ""
	gsbm.ClearPresence(v)
}

func (v *Customer) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
