// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Customer) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Name
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Name)
	// tag 2 Email
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.Email)
	return w.Err()
}

func (v *Customer) UnmarshalGSBM(r *gsbm.Reader) error {
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Name = x
			}
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Email = x
			}
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Customer) Reset() {
	v.Name = ""
	v.Email = ""
}
