// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *DeepNested) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Inner
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if v.Inner == nil {
			w.WritePresenceNil()
		} else {
			w.WritePresenceNonZero()
			if err := v.Inner.MarshalGSBM(w); err != nil {
				return err
			}
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *DeepNested) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(false)
			if err != nil {
				return err
			}
			if v.Inner != nil {
				v.Inner.ForgetPresenceTree()
			}
			switch state {
			case gsbm.PresenceNil:
				v.Inner = nil
			case gsbm.PresenceNonZero:
				v.Inner = &Branch{}
				if err := v.Inner.UnmarshalGSBM(r); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 2)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *DeepNested) Reset() {
	v.ID = ""
	if v.Inner != nil {
		v.Inner.ForgetPresenceTree()
	}
	v.Inner = nil
	gsbm.ClearPresence(v)
}

func (v *DeepNested) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}

func (v *DeepNested) ForgetPresenceTree() {
	if v.Inner != nil {
		v.Inner.ForgetPresenceTree()
	}
	gsbm.ForgetPresence(v)
}

func (v *DeepNested) ForgetValuePresenceTree() {
	gsbm.ForgetPresence(v)
}
