// Code generated by gsbmcodegen (arena mode). DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"go.flaticols.dev/gsbm/storage/gsbmarena"
)

// DecodeDeepNested decodes data into a *DeepNested allocated from a. The returned
// value, and every string/slice it transitively references, are
// invalidated by a.Release. The wire format is identical to heap mode.
func DecodeDeepNested(data []byte, a *gsbmarena.Arena) (*DeepNested, error) {
	v := gsbmarena.AllocStruct[DeepNested](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if _, _, err := r.ReadHeader(); err != nil {
		return nil, err
	}
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DecodeDeepNestedBody is the headerless variant: data is the raw root body
// without the 8-byte blob header.
func DecodeDeepNestedBody(data []byte, a *gsbmarena.Arena) (*DeepNested, error) {
	v := gsbmarena.AllocStruct[DeepNested](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DetachDeepNested returns a heap-allocated *DeepNested with no references into any
// arena. Implemented as a re-encode + heap decode round-trip so the
// heap-mode unmarshal body is the single source of truth.
func DetachDeepNested(o *DeepNested) (*DeepNested, error) {
	w := gsbm.NewWriter(nil)
	if err := o.MarshalGSBM(w); err != nil {
		return nil, err
	}
	if err := w.Err(); err != nil {
		return nil, err
	}
	dst := &DeepNested{}
	if err := gsbm.DecodeBodyInto(w.Bytes(), dst); err != nil {
		return nil, err
	}
	return dst, nil
}
