// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Item) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 SKU
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.SKU)
	// tag 2 Count
	w.WriteTag(2, gsbm.WireVarint)
	w.WriteVarint(int64(v.Count))
	return w.Err()
}

func (v *Item) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.SKU = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Count = int64(x)
			}
			gsbm.MarkPresent(v, 2)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Item) Reset() {
	v.SKU = ""
	v.Count = 0
	gsbm.ClearPresence(v)
}

func (v *Item) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}

func (v *Item) ForgetPresenceTree() {
	gsbm.ForgetPresence(v)
}

func (v *Item) ForgetValuePresenceTree() {
	gsbm.ForgetPresence(v)
}
