// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Leaflet) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Tag
	w.WriteTag(1, gsbm.WireVarint)
	w.WriteVarint(int64(v.Tag))
	return w.Err()
}

func (v *Leaflet) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Tag = int64(x)
			}
			gsbm.MarkPresent(v, 1)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Leaflet) Reset() {
	v.Tag = 0
	gsbm.ClearPresence(v)
}

func (v *Leaflet) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}

func (v *Leaflet) ForgetPresenceTree() {
	gsbm.ForgetPresence(v)
}

func (v *Leaflet) ForgetValuePresenceTree() {
	gsbm.ForgetPresence(v)
}
