// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *MapValue) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Label
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Label)
	// tag 2 Inner
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if v.Inner == nil {
			w.WritePresenceNil()
		} else {
			w.WritePresenceNonZero()
			if err := v.Inner.MarshalGSBM(w); err != nil {
				return err
			}
		}
		w.EndLengthDelim(m)
	}
	// tag 3 Items
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			inner := w.BeginLengthDelim()
			if err := v.Items[i].MarshalGSBM(w); err != nil {
				return err
			}
			w.EndLengthDelim(inner)
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *MapValue) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Label = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(false)
			if err != nil {
				return err
			}
			if v.Inner != nil {
				v.Inner.ForgetPresenceTree()
			}
			switch state {
			case gsbm.PresenceNil:
				v.Inner = nil
			case gsbm.PresenceNonZero:
				v.Inner = &Pointee{}
				if err := v.Inner.UnmarshalGSBM(r); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 2)
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if cap(v.Items) >= n {
				v.Items = v.Items[:n]
			} else {
				old := v.Items[:cap(v.Items)]
				for i := range old {
					old[i].ForgetPresenceTree()
				}
				v.Items = gsbm.MakeSlice[Leaflet](r, n)
			}
			if err := r.Err(); err != nil {
				return err
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.Items[i].Reset()
				if err := v.Items[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 3)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *MapValue) Reset() {
	v.Label = ""
	if v.Inner != nil {
		v.Inner.ForgetPresenceTree()
	}
	v.Inner = nil
	for i := range v.Items {
		v.Items[i].Reset()
	}
	v.Items = v.Items[:0]
	gsbm.ClearPresence(v)
}

func (v *MapValue) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}

func (v *MapValue) ForgetPresenceTree() {
	if v.Inner != nil {
		v.Inner.ForgetPresenceTree()
	}
	{
		all := v.Items[:cap(v.Items)]
		for i := range all {
			all[i].ForgetPresenceTree()
		}
	}
	gsbm.ForgetPresence(v)
}

func (v *MapValue) ForgetValuePresenceTree() {
	gsbm.ForgetPresence(v)
}
