// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"sort"
)

func (v *MapWithPointer) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Entries
	w.WriteTag(1, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Entries)))
		keys := make([]string, 0, len(v.Entries))
		for k := range v.Entries {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.Entries[k]
			w.WriteString(k)
			{
				m := w.BeginLengthDelim()
				if err := vv.MarshalGSBM(w); err != nil {
					return err
				}
				w.EndLengthDelim(m)
			}
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *MapWithPointer) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if len(v.Entries) > 0 {
				for _, vv := range v.Entries {
					vv.ForgetPresenceTree()
				}
				clear(v.Entries)
			}
			if n > 0 && v.Entries == nil {
				v.Entries = gsbm.MakeMap[string, MapValue](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv MapValue
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				if err := vv.UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
				if existing, ok := v.Entries[k]; ok {
					existing.ForgetPresenceTree()
				}
				v.Entries[k] = vv
				vv.ForgetValuePresenceTree()
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 1)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *MapWithPointer) Reset() {
	for _, vv := range v.Entries {
		vv.ForgetPresenceTree()
	}
	clear(v.Entries)
	gsbm.ClearPresence(v)
}

func (v *MapWithPointer) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}

func (v *MapWithPointer) ForgetPresenceTree() {
	for _, vv := range v.Entries {
		vv.ForgetPresenceTree()
	}
	gsbm.ForgetPresence(v)
}

func (v *MapWithPointer) ForgetValuePresenceTree() {
	gsbm.ForgetPresence(v)
}
