// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"sort"
)

func (v *Order) SizeGSBM() int {
	var n int
	// tag 1 ID
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.ID)
	// tag 2 Quantity
	n += gsbm.SizeTag(2, gsbm.WireVarint)
	n += gsbm.SizeVarint(int64(v.Quantity))
	// tag 3 Price
	n += gsbm.SizeTag(3, gsbm.WireFixed64)
	n += gsbm.SizeFixed64()
	// tag 4 Active
	n += gsbm.SizeTag(4, gsbm.WireVarint)
	n += gsbm.SizeBool()
	// tag 5 Note
	n += gsbm.SizeTag(5, gsbm.WireLengthDelim)
	if v.Note == nil || *v.Note == "" {
		n += gsbm.SizeLengthDelim(1)
	} else {
		n += gsbm.SizeLengthDelim(1 + gsbm.SizeString(*v.Note))
	}
	// tag 6 Customer
	n += gsbm.SizeTag(6, gsbm.WireLengthDelim)
	if v.Customer == nil {
		n += gsbm.SizeLengthDelim(1)
	} else {
		n += gsbm.SizeLengthDelim(1 + v.Customer.SizeGSBM())
	}
	// tag 7 Items
	n += gsbm.SizeTag(7, gsbm.WireLengthDelim)
	{
		body := gsbm.SizeUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			body += gsbm.SizeLengthDelim(v.Items[i].SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body)
	}
	// tag 8 Tags
	n += gsbm.SizeTag(8, gsbm.WireLengthDelim)
	{
		body := gsbm.SizeUvarint(uint64(len(v.Tags)))
		for k, vv := range v.Tags {
			body += gsbm.SizeString(k)
			body += gsbm.SizeVarint(int64(vv))
		}
		n += gsbm.SizeLengthDelim(body)
	}
	// tag 9 Payload
	n += gsbm.SizeTag(9, gsbm.WireLengthDelim)
	n += gsbm.SizeBytes(v.Payload)
	// tag 10 Total
	n += gsbm.SizeTag(10, gsbm.WireLengthDelim)
	n += gsbm.SizeLengthDelim(v.Total.SizeGSBM())
	// tag 11 Counts
	n += gsbm.SizeTag(11, gsbm.WireLengthDelim)
	{
		body := gsbm.SizeUvarint(uint64(len(v.Counts)))
		for i := range v.Counts {
			body += gsbm.SizeVarint(int64(v.Counts[i]))
		}
		n += gsbm.SizeLengthDelim(body)
	}
	// tag 12 Aliases
	n += gsbm.SizeTag(12, gsbm.WireLengthDelim)
	{
		body := gsbm.SizeUvarint(uint64(len(v.Aliases)))
		for k, vv := range v.Aliases {
			body += gsbm.SizeString(k)
			body += gsbm.SizeString((string)(vv))
		}
		n += gsbm.SizeLengthDelim(body)
	}
	// tag 13 Qty
	n += gsbm.SizeTag(13, gsbm.WireVarint)
	n += gsbm.SizeVarint(int64((int64)(v.Qty)))
	// tag 14 OptQty
	n += gsbm.SizeTag(14, gsbm.WireLengthDelim)
	if v.OptQty == nil {
		n += gsbm.SizeLengthDelim(1)
	} else {
		n += gsbm.SizeLengthDelim(1 + gsbm.SizeVarint(int64((int64)(*v.OptQty))))
	}
	// tag 15 QtyList
	n += gsbm.SizeTag(15, gsbm.WireLengthDelim)
	{
		body := gsbm.SizeUvarint(uint64(len(v.QtyList)))
		for i := range v.QtyList {
			body += gsbm.SizeVarint(int64((int64)(v.QtyList[i])))
		}
		n += gsbm.SizeLengthDelim(body)
	}
	// tag 16 OptLabel
	n += gsbm.SizeTag(16, gsbm.WireLengthDelim)
	if v.OptLabel == nil {
		n += gsbm.SizeLengthDelim(1)
	} else {
		n += gsbm.SizeLengthDelim(1 + gsbm.SizeString((string)(*v.OptLabel)))
	}
	// tag 17 LabelList
	n += gsbm.SizeTag(17, gsbm.WireLengthDelim)
	{
		body := gsbm.SizeUvarint(uint64(len(v.LabelList)))
		for i := range v.LabelList {
			body += gsbm.SizeString((string)(v.LabelList[i]))
		}
		n += gsbm.SizeLengthDelim(body)
	}
	// tag 18 OptPayload
	n += gsbm.SizeTag(18, gsbm.WireLengthDelim)
	if v.OptPayload == nil || len(*v.OptPayload) == 0 {
		n += gsbm.SizeLengthDelim(1)
	} else {
		n += gsbm.SizeLengthDelim(1 + gsbm.SizeBytes(*v.OptPayload))
	}
	return n
}

func (v *Order) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Quantity
	w.WriteTag(2, gsbm.WireVarint)
	w.WriteVarint(int64(v.Quantity))
	// tag 3 Price
	w.WriteTag(3, gsbm.WireFixed64)
	w.WriteFloat64(v.Price)
	// tag 4 Active
	w.WriteTag(4, gsbm.WireVarint)
	w.WriteBool(v.Active)
	// tag 5 Note
	w.WriteTag(5, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		switch {
		case v.Note == nil:
			w.WritePresenceNil()
		case *v.Note == "":
			w.WritePresenceZero()
		default:
			w.WritePresenceNonZero()
			w.WriteString(*v.Note)
		}
		w.EndLengthDelim(m)
	}
	// tag 6 Customer
	w.WriteTag(6, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if v.Customer == nil {
			w.WritePresenceNil()
		} else {
			w.WritePresenceNonZero()
			if err := v.Customer.MarshalGSBM(w); err != nil {
				return err
			}
		}
		w.EndLengthDelim(m)
	}
	// tag 7 Items
	w.WriteTag(7, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			inner := w.BeginLengthDelim()
			if err := v.Items[i].MarshalGSBM(w); err != nil {
				return err
			}
			w.EndLengthDelim(inner)
		}
		w.EndLengthDelim(m)
	}
	// tag 8 Tags
	w.WriteTag(8, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Tags)))
		keys := make([]string, 0, len(v.Tags))
		for k := range v.Tags {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.Tags[k]
			w.WriteString(k)
			w.WriteVarint(int64(vv))
		}
		w.EndLengthDelim(m)
	}
	// tag 9 Payload
	w.WriteTag(9, gsbm.WireLengthDelim)
	w.WriteBytes(v.Payload)
	// tag 10 Total
	w.WriteTag(10, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if err := v.Total.MarshalGSBM(w); err != nil {
			return err
		}
		w.EndLengthDelim(m)
	}
	// tag 11 Counts
	w.WriteTag(11, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Counts)))
		for i := range v.Counts {
			w.WriteVarint(int64(v.Counts[i]))
		}
		w.EndLengthDelim(m)
	}
	// tag 12 Aliases
	w.WriteTag(12, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Aliases)))
		keys := make([]string, 0, len(v.Aliases))
		for k := range v.Aliases {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.Aliases[k]
			w.WriteString(k)
			w.WriteString((string)(vv))
		}
		w.EndLengthDelim(m)
	}
	// tag 13 Qty
	w.WriteTag(13, gsbm.WireVarint)
	w.WriteVarint(int64((int64)(v.Qty)))
	// tag 14 OptQty
	w.WriteTag(14, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if v.OptQty == nil {
			w.WritePresenceNil()
		} else {
			w.WritePresenceNonZero()
			w.WriteVarint(int64((int64)(*v.OptQty)))
		}
		w.EndLengthDelim(m)
	}
	// tag 15 QtyList
	w.WriteTag(15, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.QtyList)))
		for i := range v.QtyList {
			w.WriteVarint(int64((int64)(v.QtyList[i])))
		}
		w.EndLengthDelim(m)
	}
	// tag 16 OptLabel
	w.WriteTag(16, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if v.OptLabel == nil {
			w.WritePresenceNil()
		} else {
			w.WritePresenceNonZero()
			w.WriteString((string)(*v.OptLabel))
		}
		w.EndLengthDelim(m)
	}
	// tag 17 LabelList
	w.WriteTag(17, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.LabelList)))
		for i := range v.LabelList {
			w.WriteString((string)(v.LabelList[i]))
		}
		w.EndLengthDelim(m)
	}
	// tag 18 OptPayload
	w.WriteTag(18, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		switch {
		case v.OptPayload == nil:
			w.WritePresenceNil()
		case len(*v.OptPayload) == 0:
			w.WritePresenceZero()
		default:
			w.WritePresenceNonZero()
			w.WriteBytes(*v.OptPayload)
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Order) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Quantity = int64(x)
			}
			gsbm.MarkPresent(v, 2)
		case 3:
			if wt != gsbm.WireFixed64 {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadFloat64()
				if err != nil {
					return err
				}
				v.Price = x
			}
			gsbm.MarkPresent(v, 3)
		case 4:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Active = x
			}
			gsbm.MarkPresent(v, 4)
		case 5:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(true)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.Note = nil
			case gsbm.PresenceZero:
				var z string
				v.Note = &z
			case gsbm.PresenceNonZero:
				var tmp string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					tmp = x
				}
				v.Note = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 5)
		case 6:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(false)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.Customer = nil
			case gsbm.PresenceNonZero:
				v.Customer = &Customer{}
				if err := v.Customer.UnmarshalGSBM(r); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 6)
		case 7:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Items) >= n {
					v.Items = v.Items[:n]
				} else {
					v.Items = gsbm.MakeSlice[Item](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.Items[i].Reset()
				if err := v.Items[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 7)
		case 8:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.Tags == nil {
				v.Tags = gsbm.MakeMap[string, int64](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					vv = int64(x)
				}
				v.Tags[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 8)
		case 9:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			b, err := r.ReadBytes()
			if err != nil {
				return err
			}
			v.Payload = append(v.Payload[:0], b...)
			gsbm.MarkPresent(v, 9)
		case 10:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			if err := v.Total.UnmarshalGSBM(r); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 10)
		case 11:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Counts) >= n {
					v.Counts = v.Counts[:n]
				} else {
					v.Counts = gsbm.MakeSlice[int64](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					v.Counts[i] = int64(x)
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 11)
		case 12:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.Aliases == nil {
				v.Aliases = gsbm.MakeMap[string, Label](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv Label
				{
					var tmp string
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						tmp = x
					}
					vv = Label(tmp)
				}
				v.Aliases[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 12)
		case 13:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			var tmp int64
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				tmp = int64(x)
			}
			v.Qty = Quantity(tmp)
			gsbm.MarkPresent(v, 13)
		case 14:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(false)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.OptQty = nil
			case gsbm.PresenceNonZero:
				var u int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					u = int64(x)
				}
				tmp := Quantity(u)
				v.OptQty = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 14)
		case 15:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.QtyList) >= n {
					v.QtyList = v.QtyList[:n]
				} else {
					v.QtyList = gsbm.MakeSlice[Quantity](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				var u int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					u = int64(x)
				}
				v.QtyList[i] = Quantity(u)
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 15)
		case 16:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(false)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.OptLabel = nil
			case gsbm.PresenceNonZero:
				var u string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					u = x
				}
				tmp := Label(u)
				v.OptLabel = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 16)
		case 17:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.LabelList) >= n {
					v.LabelList = v.LabelList[:n]
				} else {
					v.LabelList = gsbm.MakeSlice[Label](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				var u string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					u = x
				}
				v.LabelList[i] = Label(u)
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 17)
		case 18:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(true)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.OptPayload = nil
			case gsbm.PresenceZero:
				z := []byte{}
				v.OptPayload = &z
			case gsbm.PresenceNonZero:
				b, err := r.ReadBytes()
				if err != nil {
					return err
				}
				cp := append([]byte(nil), b...)
				v.OptPayload = &cp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 18)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Order) Reset() {
	v.ID = ""
	v.Quantity = 0
	v.Price = 0
	v.Active = false
	v.Note = nil
	v.Customer = nil
	for i := range v.Items {
		v.Items[i].Reset()
	}
	v.Items = v.Items[:0]
	clear(v.Tags)
	v.Payload = v.Payload[:0]
	v.Total.Reset()
	v.Counts = v.Counts[:0]
	clear(v.Aliases)
	v.Qty = Quantity(0)
	v.OptQty = nil
	v.QtyList = v.QtyList[:0]
	v.OptLabel = nil
	v.LabelList = v.LabelList[:0]
	v.OptPayload = nil
	gsbm.ClearPresence(v)
}

func (v *Order) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
