// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Renamed) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 LegacyCode: deprecated, compat_write (rollback window)
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.LegacyCode)
	// tag 3 RetailCode
	w.WriteTag(3, gsbm.WireLengthDelim)
	w.WriteString(v.RetailCode)
	return w.Err()
}

func (v *Renamed) UnmarshalGSBM(r *gsbm.Reader) error {
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.LegacyCode = x
			}
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.RetailCode = x
			}
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Renamed) Reset() {
	v.ID = ""
	v.LegacyCode = ""
	v.RetailCode = ""
}
