// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Renamed) SizeGSBM() int {
	n := 0
	// tag 1 ID
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.ID)
	// tag 2 LegacyCode: deprecated, compat_write (rollback window)
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.LegacyCode)
	// tag 3 RetailCode
	n += gsbm.SizeTag(3, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.RetailCode)
	return n
}

func (v *Renamed) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 LegacyCode: deprecated, compat_write (rollback window)
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.LegacyCode)
	// tag 3 RetailCode
	w.WriteTag(3, gsbm.WireLengthDelim)
	w.WriteString(v.RetailCode)
	return w.Err()
}

func (v *Renamed) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.LegacyCode = x
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.RetailCode = x
			}
			present[0] |= 1 << 2
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Renamed) Reset() {
	v.ID = ""
	v.LegacyCode = ""
	v.RetailCode = ""
	gsbm.ClearPresence(v)
}

func (v *Renamed) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
