// Code generated by gsbmcodegen (arena mode). DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"go.flaticols.dev/gsbm/storage/gsbmarena"
)

// DecodeRenamed decodes data into a *Renamed allocated from a. The returned
// value, and every string/slice it transitively references, are
// invalidated by a.Release. The wire format is identical to heap mode.
func DecodeRenamed(data []byte, a *gsbmarena.Arena) (*Renamed, error) {
	v := gsbmarena.AllocStruct[Renamed](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if _, _, _, err := r.ReadHeader(); err != nil {
		return nil, err
	}
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DecodeRenamedBody is the headerless variant: data is the raw root body
// without the 12-byte blob header.
func DecodeRenamedBody(data []byte, a *gsbmarena.Arena) (*Renamed, error) {
	v := gsbmarena.AllocStruct[Renamed](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DetachRenamed returns a heap-allocated *Renamed with no references into any
// arena. Implemented as a re-encode + heap decode round-trip so the
// heap-mode unmarshal body is the single source of truth.
func DetachRenamed(o *Renamed) (*Renamed, error) {
	w := gsbm.NewWriter(nil)
	if err := o.MarshalGSBM(w); err != nil {
		return nil, err
	}
	if err := w.Err(); err != nil {
		return nil, err
	}
	dst := &Renamed{}
	if err := gsbm.DecodeBodyInto(w.Bytes(), dst); err != nil {
		return nil, err
	}
	return dst, nil
}
