// Code generated by gsbmcodegen. DO NOT EDIT.

package sample

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Total) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *Total) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Currency
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Currency)
	// tag 2 Amount
	w.WriteTag(2, gsbm.WireFixed64)
	w.WriteFloat64(v.Amount)
	return w.Err()
}

func (v *Total) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Currency = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireFixed64 {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadFloat64()
				if err != nil {
					return err
				}
				v.Amount = x
			}
			present[0] |= 1 << 1
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Total) Reset() {
	v.Currency = ""
	v.Amount = 0
	gsbm.ClearPresence(v)
}

func (v *Total) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
