// Code generated by gsbmcodegen. DO NOT EDIT.

package common

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Value) SizeGSBM() int {
	n := 0
	// tag 1 Token
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Token)
	// tag 2 Score
	n += gsbm.SizeTag(2, gsbm.WireFixed64)
	n += gsbm.SizeFixed64()
	return n
}

func (v *Value) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Token
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Token)
	// tag 2 Score
	w.WriteTag(2, gsbm.WireFixed64)
	w.WriteFloat64(v.Score)
	return w.Err()
}

func (v *Value) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Token = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireFixed64 {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadFloat64()
				if err != nil {
					return err
				}
				v.Score = x
			}
			present[0] |= 1 << 1
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Value) Reset() {
	v.Token = ""
	v.Score = 0
	gsbm.ClearPresence(v)
}

func (v *Value) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
