// Code generated by gsbmcodegen. DO NOT EDIT.

package after

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Shipment) SizeGSBM() int {
	n := 0
	// tag 1 Carrier
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Carrier)
	// tag 2 TrackingID
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.TrackingID)
	// tag 3 Weight
	n += gsbm.SizeTag(3, gsbm.WireVarint)
	n += gsbm.SizeVarint(int64(v.Weight))
	return n
}

func (v *Shipment) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Carrier
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Carrier)
	// tag 2 TrackingID
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.TrackingID)
	// tag 3 Weight
	w.WriteTag(3, gsbm.WireVarint)
	w.WriteVarint(int64(v.Weight))
	return w.Err()
}

func (v *Shipment) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Carrier = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.TrackingID = x
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Weight = int64(x)
			}
			present[0] |= 1 << 2
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Shipment) Reset() {
	v.Carrier = ""
	v.TrackingID = ""
	v.Weight = 0
	gsbm.ClearPresence(v)
}

func (v *Shipment) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
