// Code generated by gsbmcodegen. DO NOT EDIT.

package importcollision

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"go.flaticols.dev/gsbm/tools/gsbmcodegen/fixtures/importcollision/pkg/a/common"
	bcommon "go.flaticols.dev/gsbm/tools/gsbmcodegen/fixtures/importcollision/pkg/b/common"
)

func (v *Record) SizeGSBM() int {
	n := 0
	// tag 1 A
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.A)))
		for i := range v.A {
			body_1 += gsbm.SizeLengthDelim(v.A[i].SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 2 B
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.B)))
		for i := range v.B {
			body_1 += gsbm.SizeLengthDelim(v.B[i].SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	return n
}

func (v *Record) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 A
	w.WriteTag(1, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.A)))
		for i := range v.A {
			body_1 += gsbm.SizeLengthDelim(v.A[i].SizeGSBM())
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.A)))
		for i := range v.A {
			w.WriteLength(v.A[i].SizeGSBM())
			if err := v.A[i].MarshalGSBM(w); err != nil {
				return err
			}
		}
	}
	// tag 2 B
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.B)))
		for i := range v.B {
			body_1 += gsbm.SizeLengthDelim(v.B[i].SizeGSBM())
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.B)))
		for i := range v.B {
			w.WriteLength(v.B[i].SizeGSBM())
			if err := v.B[i].MarshalGSBM(w); err != nil {
				return err
			}
		}
	}
	return w.Err()
}

func (v *Record) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.A) >= n {
					v.A = v.A[:n]
				} else {
					v.A = gsbm.MakeSlice[common.Value](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.A[i].Reset()
				if err := v.A[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.B) >= n {
					v.B = v.B[:n]
				} else {
					v.B = gsbm.MakeSlice[bcommon.Value](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.B[i].Reset()
				if err := v.B[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 1
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Record) Reset() {
	for i := range v.A {
		v.A[i].Reset()
	}
	v.A = v.A[:0]
	for i := range v.B {
		v.B[i].Reset()
	}
	v.B = v.B[:0]
	gsbm.ClearPresence(v)
}

func (v *Record) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
