package odmcodegen_test

import (
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/flaticols/gsbm/tools/odmcodegen"
	"github.com/flaticols/gsbm/tools/odmschema"
)

// fixtureDir returns the absolute path of tools/odmcodegen/fixtures/sample
// based on the test source location, so the test runs regardless of cwd.
func fixtureDir(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Join(filepath.Dir(thisFile), "fixtures", "sample")
}

// loadHandwrittenOnly parses the fixture's handwritten Go files (types.go
// and friends) but skips committed *_odm.go siblings. The committed files
// import storage/odm via the module path, which odmschema.LoadFromDirs's
// stdlib-only importer can't resolve. The handwritten types.go has no
// imports, so this lightweight loader is sufficient for the codegen test.
func loadHandwrittenOnly(t *testing.T, dir string) *odmschema.PackageSet {
	t.Helper()
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read %s: %v", dir, err)
	}
	var files []*ast.File
	var pkgName string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		if strings.HasSuffix(e.Name(), "_test.go") || strings.HasSuffix(e.Name(), "_odm.go") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			t.Fatalf("parse %s: %v", path, err)
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		}
		files = append(files, f)
	}
	conf := &types.Config{Importer: importer.Default()}
	info := &types.Info{
		Types:      map[ast.Expr]types.TypeAndValue{},
		Defs:       map[*ast.Ident]types.Object{},
		Uses:       map[*ast.Ident]types.Object{},
		Implicits:  map[ast.Node]types.Object{},
		Selections: map[*ast.SelectorExpr]*types.Selection{},
		Scopes:     map[ast.Node]*types.Scope{},
		Instances:  map[*ast.Ident]types.Instance{},
	}
	pkgPath := "github.com/flaticols/gsbm/tools/odmcodegen/fixtures/sample"
	pkg, err := conf.Check(pkgPath, fset, files, info)
	if err != nil {
		t.Fatalf("typecheck: %v", err)
	}
	return &odmschema.PackageSet{
		Fset: fset,
		Packages: []*odmschema.Package{{
			Path:  pkg.Path(),
			Name:  pkg.Name(),
			Files: files,
			Info:  info,
			Pkg:   pkg,
		}},
	}
}

// TestGoldenSample asserts every committed <type>_odm.go is byte-identical
// to what Generate produces from the live fixture. This is the contract
// that lets us hand-edit the fixture and regenerate without surprises.
func TestGoldenSample(t *testing.T) {
	dir := fixtureDir(t)
	ps := loadHandwrittenOnly(t, dir)
	res := odmschema.Analyze(ps)
	if len(res.Issues) > 0 {
		t.Fatalf("schema issues: %s", odmschema.FormatIssues(res.Issues))
	}
	files, err := odmcodegen.Generate(ps, res.Schema)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if len(files) == 0 {
		t.Fatal("no files generated")
	}
	for _, gf := range files {
		want, err := os.ReadFile(gf.Path)
		if err != nil {
			t.Errorf("%s: missing committed golden — write the file then re-run: %v", gf.Path, err)
			t.Logf("--- generated %s ---\n%s", gf.Path, gf.Contents)
			continue
		}
		if string(want) != string(gf.Contents) {
			t.Errorf("%s: drifted from golden", gf.Path)
			t.Logf("--- generated ---\n%s", gf.Contents)
			t.Logf("--- golden ---\n%s", want)
		}
	}
}

// TestGenerateSkipsExternalAndOpaque ensures the generator only produces
// files for in-set, non-opaque, non-generic structs.
func TestGenerateSkipsExternalAndOpaque(t *testing.T) {
	dir := fixtureDir(t)
	ps := loadHandwrittenOnly(t, dir)
	res := odmschema.Analyze(ps)
	files, err := odmcodegen.Generate(ps, res.Schema)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	for _, gf := range files {
		if !strings.HasSuffix(gf.Path, "_odm.go") {
			t.Errorf("unexpected output filename: %s", gf.Path)
		}
		if !strings.Contains(string(gf.Contents), "Code generated by odmcodegen") {
			t.Errorf("%s: missing generated header", gf.Path)
		}
	}
}
