// Package odmcodegen emits MarshalODM / UnmarshalODM companion files for
// the type closure discovered by tools/odmschema. The generator consumes
// the typechecked PackageSet plus the validated Schema and produces one
// generated Go file per non-generic struct in the closure, named
// <lowercase_typename>_odm.go and placed next to the handwritten source
// file. Generated code uses only storage/odm primitives — no reflection,
// all tag values inlined as integer literals.
//
// Scope notes:
//   - Generic origin types (those with type parameters) are skipped here.
//     Go does not allow a generic method body to dispatch on its type
//     parameter, so per-instantiation free functions would be required.
//     Tracked as a follow-up; no generics appear in the M3 closure tested.
//   - Opaque structs (//odm:opaque) are skipped — the schema flags them
//     so the codegen leaves their (re)marshaling to handwritten code.
//   - External types (declared in packages outside the input set) are
//     skipped because we cannot place generated files into foreign trees.
package odmcodegen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"path/filepath"
	"sort"
	"strings"

	"github.com/flaticols/gsbm/tools/odmschema"
)

// GeneratedFile is one emitted source file. The Path is absolute (taken
// from the source file's filesystem location) so callers can pass the
// list straight to a file writer or compare against committed goldens.
type GeneratedFile struct {
	Path     string
	Package  string
	TypeName string
	Contents []byte
}

// Generate runs the full codegen pass: discover writable named structs in
// the closure, find each one's source location and import path, and emit
// a companion file per type. The result is sorted by Path for stable
// ordering across runs.
func Generate(ps *odmschema.PackageSet, schema *odmschema.Schema) ([]GeneratedFile, error) {
	if ps == nil || schema == nil {
		return nil, fmt.Errorf("odmcodegen: nil input")
	}
	allowed := map[string]bool{}
	for _, p := range ps.Packages {
		allowed[p.Path] = true
	}

	var files []GeneratedFile
	for _, sd := range schema.Structs {
		if sd.Opaque {
			continue
		}
		if len(sd.Generic) > 0 {
			// Generic origin types skipped — see scope notes above.
			continue
		}
		if !allowed[sd.Type.PkgPath] {
			continue
		}
		for _, fd := range sd.Fields {
			if fd.CycleBreak {
				return nil, fmt.Errorf("odmcodegen: %s.%s: //odm:cycle_break_via_id requires ID-reference codegen which is not yet implemented", sd.Type.Name, fd.Name)
			}
		}
		named, pkg := lookupNamed(ps, sd.Type)
		if named == nil {
			continue
		}
		path := ps.Fset.Position(named.Obj().Pos()).Filename
		if path == "" {
			continue
		}
		dir := filepath.Dir(path)
		fname := strings.ToLower(sd.Type.Name) + "_odm.go"
		out, err := emitFile(pkg, named, sd)
		if err != nil {
			return nil, fmt.Errorf("odmcodegen: %s: %w", sd.Type.Name, err)
		}
		files = append(files, GeneratedFile{
			Path:     filepath.Join(dir, fname),
			Package:  pkg.Name(),
			TypeName: sd.Type.Name,
			Contents: out,
		})
	}
	sort.SliceStable(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

func lookupNamed(ps *odmschema.PackageSet, ref odmschema.TypeRef) (*types.Named, *types.Package) {
	for _, p := range ps.Packages {
		if p.Path != ref.PkgPath {
			continue
		}
		obj := p.Pkg.Scope().Lookup(ref.Name)
		if obj == nil {
			return nil, nil
		}
		tn, ok := obj.(*types.TypeName)
		if !ok {
			return nil, nil
		}
		named, ok := tn.Type().(*types.Named)
		if !ok {
			return nil, nil
		}
		return named, p.Pkg
	}
	return nil, nil
}

// emitFile produces a complete formatted Go source file for one struct.
func emitFile(pkg *types.Package, named *types.Named, sd *odmschema.StructDecl) ([]byte, error) {
	str, _ := named.Underlying().(*types.Struct)
	if str == nil {
		return nil, fmt.Errorf("type %s is not a struct", named.Obj().Name())
	}
	e := &emitter{pkg: pkg, imports: map[string]string{}}
	e.addImport("github.com/flaticols/gsbm/storage/odm")

	// Emit method bodies into a side buffer; we'll prepend the header and
	// imports once we know which packages were referenced.
	var body bytes.Buffer
	if err := e.emitMarshal(&body, named, str, sd); err != nil {
		return nil, err
	}
	body.WriteString("\n")
	if err := e.emitUnmarshal(&body, named, str, sd); err != nil {
		return nil, err
	}
	body.WriteString("\n")
	if err := e.emitReset(&body, named, str, sd); err != nil {
		return nil, err
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by odmcodegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", pkg.Name())
	if len(e.imports) > 0 {
		out.WriteString("import (\n")
		paths := make([]string, 0, len(e.imports))
		for p := range e.imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			alias := e.imports[p]
			if alias == "" || alias == defaultImportName(p) {
				fmt.Fprintf(&out, "\t%q\n", p)
			} else {
				fmt.Fprintf(&out, "\t%s %q\n", alias, p)
			}
		}
		out.WriteString(")\n\n")
	}
	out.Write(body.Bytes())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		// Surface unformatted content for debugging.
		return out.Bytes(), fmt.Errorf("format: %w", err)
	}
	return formatted, nil
}

// emitter accumulates per-file state.
type emitter struct {
	pkg     *types.Package
	imports map[string]string // pkgPath → alias ("" = default)
}

func (e *emitter) addImport(path string) string {
	if path == e.pkg.Path() {
		return ""
	}
	if _, ok := e.imports[path]; !ok {
		e.imports[path] = ""
	}
	return defaultImportName(path)
}

func defaultImportName(path string) string {
	if path == "" {
		return ""
	}
	last := path
	if i := strings.LastIndex(path, "/"); i >= 0 {
		last = path[i+1:]
	}
	return last
}

// typeExpr returns the Go source expression for a type, qualifying named
// references against the current package and tracking imports.
func (e *emitter) typeExpr(t types.Type) string {
	switch tt := t.(type) {
	case *types.Basic:
		return tt.Name()
	case *types.Named:
		obj := tt.Obj()
		if obj.Pkg() == nil || obj.Pkg().Path() == e.pkg.Path() {
			return obj.Name()
		}
		alias := e.addImport(obj.Pkg().Path())
		return alias + "." + obj.Name()
	case *types.Pointer:
		return "*" + e.typeExpr(tt.Elem())
	case *types.Slice:
		if isByteType(tt.Elem()) {
			return "[]byte"
		}
		return "[]" + e.typeExpr(tt.Elem())
	case *types.Array:
		return fmt.Sprintf("[%d]%s", tt.Len(), e.typeExpr(tt.Elem()))
	case *types.Map:
		return fmt.Sprintf("map[%s]%s", e.typeExpr(tt.Key()), e.typeExpr(tt.Elem()))
	default:
		return tt.String()
	}
}

func isByteType(t types.Type) bool {
	b, ok := t.(*types.Basic)
	if !ok {
		return false
	}
	return b.Kind() == types.Byte || b.Kind() == types.Uint8
}
