// Code generated by gsbmcodegen. DO NOT EDIT.

package cyclebreak

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Item) SizeGSBM() int {
	n := 0
	// tag 1 ID
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.ID)
	// tag 2 Label
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Label)
	// tag 3 Previous
	if v.Previous != nil {
		n += gsbm.SizeTag(3, gsbm.WireLengthDelim)
		n += gsbm.SizeString(v.Previous.ID)
	}
	return n
}

func (v *Item) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Label
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.Label)
	// tag 3 Previous
	if v.Previous != nil {
		w.WriteTag(3, gsbm.WireLengthDelim)
		w.WriteString(v.Previous.ID)
	}
	return w.Err()
}

func (v *Item) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Label = x
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			v.Previous = &Item{}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Previous.ID = x
			}
			present[0] |= 1 << 2
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Item) Reset() {
	v.ID = ""
	v.Label = ""
	v.Previous = nil
	gsbm.ClearPresence(v)
}

func (v *Item) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
