// Code generated by gsbmcodegen. DO NOT EDIT.

package common

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Value) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *Value) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Label
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Label)
	// tag 2 Count
	w.WriteTag(2, gsbm.WireVarint)
	w.WriteVarint(int64(v.Count))
	return w.Err()
}

func (v *Value) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Label = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Count = int64(x)
			}
			present[0] |= 1 << 1
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Value) Reset() {
	v.Label = ""
	v.Count = 0
	gsbm.ClearPresence(v)
}

func (v *Value) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
