// Code generated by gsbmcodegen. DO NOT EDIT.

package after

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Shipment) SizeGSBM() int {
	var n int
	// tag 1 ID
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.ID)
	// tag 2 Carrier: deprecated, compat_write (rollback window)
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Carrier)
	// tag 3 CarrierCode
	n += gsbm.SizeTag(3, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.CarrierCode)
	return n
}

func (v *Shipment) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Carrier: deprecated, compat_write (rollback window)
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.Carrier)
	// tag 3 CarrierCode
	w.WriteTag(3, gsbm.WireLengthDelim)
	w.WriteString(v.CarrierCode)
	return w.Err()
}

func (v *Shipment) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Carrier = x
			}
			gsbm.MarkPresent(v, 2)
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.CarrierCode = x
			}
			gsbm.MarkPresent(v, 3)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Shipment) Reset() {
	v.ID = ""
	v.Carrier = ""
	v.CarrierCode = ""
	gsbm.ClearPresence(v)
}

func (v *Shipment) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
