// Code generated by gsbmcodegen. DO NOT EDIT.

package intwidth

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"math"
)

func (v *Record) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *Record) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Small
	w.WriteTag(1, gsbm.WireVarint)
	if int64(v.Small) < math.MinInt32 || int64(v.Small) > math.MaxInt32 {
		return gsbm.ErrIntegerOverflow
	}
	w.WriteVarint(int64(v.Small))
	// tag 2 Large
	w.WriteTag(2, gsbm.WireVarint)
	w.WriteVarint(int64(v.Large))
	return w.Err()
}

func (v *Record) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				if x < math.MinInt32 || x > math.MaxInt32 {
					return gsbm.ErrIntegerOverflow
				}
				v.Small = int(x)
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Large = int(x)
			}
			present[0] |= 1 << 1
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Record) Reset() {
	v.Small = 0
	v.Large = 0
	gsbm.ClearPresence(v)
}

func (v *Record) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
