// Code generated by gsbmcodegen. DO NOT EDIT.

package intwidth

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"math"
)

func (v *WideRecord) SizeGSBM() int {
	n := 0
	// tag 1 Uint
	n += gsbm.SizeTag(1, gsbm.WireVarint)
	n += gsbm.SizeUvarint(uint64(v.Uint))
	// tag 2 Uintptr
	n += gsbm.SizeTag(2, gsbm.WireVarint)
	n += gsbm.SizeUvarint(uint64(v.Uintptr))
	// tag 3 NarrowSigned
	n += gsbm.SizeTag(3, gsbm.WireVarint)
	n += gsbm.SizeVarint(int64(v.NarrowSigned))
	// tag 4 NarrowUnsigned
	n += gsbm.SizeTag(4, gsbm.WireVarint)
	n += gsbm.SizeUvarint(uint64(v.NarrowUnsigned))
	// tag 5 Identity
	n += gsbm.SizeTag(5, gsbm.WireVarint)
	n += gsbm.SizeVarint(int64(v.Identity))
	// tag 6 NamedAlias
	n += gsbm.SizeTag(6, gsbm.WireVarint)
	n += gsbm.SizeVarint(int64(v.NamedAlias))
	return n
}

func (v *WideRecord) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Uint
	w.WriteTag(1, gsbm.WireVarint)
	w.WriteUvarint(uint64(v.Uint))
	// tag 2 Uintptr
	w.WriteTag(2, gsbm.WireVarint)
	w.WriteUvarint(uint64(v.Uintptr))
	// tag 3 NarrowSigned
	w.WriteTag(3, gsbm.WireVarint)
	if int64(v.NarrowSigned) < math.MinInt16 || int64(v.NarrowSigned) > math.MaxInt16 {
		return gsbm.ErrIntegerOverflow
	}
	w.WriteVarint(int64(v.NarrowSigned))
	// tag 4 NarrowUnsigned
	w.WriteTag(4, gsbm.WireVarint)
	if uint64(v.NarrowUnsigned) > math.MaxUint8 {
		return gsbm.ErrIntegerOverflow
	}
	w.WriteUvarint(uint64(v.NarrowUnsigned))
	// tag 5 Identity
	w.WriteTag(5, gsbm.WireVarint)
	w.WriteVarint(int64(v.Identity))
	// tag 6 NamedAlias
	w.WriteTag(6, gsbm.WireVarint)
	if int64(v.NamedAlias) < math.MinInt32 || int64(v.NamedAlias) > math.MaxInt32 {
		return gsbm.ErrIntegerOverflow
	}
	w.WriteVarint(int64(v.NamedAlias))
	return w.Err()
}

func (v *WideRecord) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadUvarint()
				if err != nil {
					return err
				}
				if x > math.MaxUint {
					return gsbm.ErrIntegerOverflow
				}
				v.Uint = uint(x)
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadUvarint()
				if err != nil {
					return err
				}
				if x > math.MaxUint {
					return gsbm.ErrIntegerOverflow
				}
				v.Uintptr = uintptr(x)
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				if x < math.MinInt16 || x > math.MaxInt16 {
					return gsbm.ErrIntegerOverflow
				}
				v.NarrowSigned = int64(x)
			}
			present[0] |= 1 << 2
		case 4:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadUvarint()
				if err != nil {
					return err
				}
				if x > math.MaxUint8 {
					return gsbm.ErrIntegerOverflow
				}
				v.NarrowUnsigned = x
			}
			present[0] |= 1 << 3
		case 5:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				if x < math.MinInt32 || x > math.MaxInt32 {
					return gsbm.ErrIntegerOverflow
				}
				v.Identity = int32(x)
			}
			present[0] |= 1 << 4
		case 6:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			var tmp int64
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				if x < math.MinInt32 || x > math.MaxInt32 {
					return gsbm.ErrIntegerOverflow
				}
				tmp = int64(x)
			}
			v.NamedAlias = UserID(tmp)
			present[0] |= 1 << 5
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *WideRecord) Reset() {
	v.Uint = 0
	v.Uintptr = 0
	v.NarrowSigned = 0
	v.NarrowUnsigned = 0
	v.Identity = 0
	v.NamedAlias = UserID(0)
	gsbm.ClearPresence(v)
}

func (v *WideRecord) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
