// Code generated by gsbmcodegen. DO NOT EDIT.

package before

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Shipment) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Carrier
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Carrier)
	// tag 2 TrackingID
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.TrackingID)
	return w.Err()
}

func (v *Shipment) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Carrier = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.TrackingID = x
			}
			gsbm.MarkPresent(v, 2)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Shipment) Reset() {
	v.Carrier = ""
	v.TrackingID = ""
	gsbm.ClearPresence(v)
}

func (v *Shipment) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
