// Code generated by gsbmcodegen. DO NOT EDIT.

package borrowstrings

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"sort"
	"unsafe"
)

func (v *BorrowRecord) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *BorrowRecord) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Note
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		switch {
		case v.Note == nil:
			w.WritePresenceNil()
		case *v.Note == "":
			w.WritePresenceZero()
		default:
			w.WritePresenceNonZero()
			w.WriteString(*v.Note)
		}
		w.EndLengthDelim(m)
	}
	// tag 3 Names
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Names)))
		for i := range v.Names {
			w.WriteString(v.Names[i])
		}
		w.EndLengthDelim(m)
	}
	// tag 4 Labels
	w.WriteTag(4, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Labels)))
		for i := range v.Labels {
			w.WriteString((string)(v.Labels[i]))
		}
		w.EndLengthDelim(m)
	}
	// tag 5 Tags
	w.WriteTag(5, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Tags)))
		keys := make([]string, 0, len(v.Tags))
		for k := range v.Tags {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.Tags[k]
			w.WriteString(k)
			w.WriteString(vv)
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *BorrowRecord) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				b, err := r.ReadBytes()
				if err != nil {
					return err
				}
				if r.Allocator() != nil {
					v.ID = r.AcquireString(b)
				} else if len(b) == 0 {
					v.ID = ""
				} else {
					v.ID = unsafe.String(&b[0], len(b))
				}
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(true)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.Note = nil
			case gsbm.PresenceZero:
				var z string
				v.Note = &z
			case gsbm.PresenceNonZero:
				var tmp string
				{
					b, err := r.ReadBytes()
					if err != nil {
						return err
					}
					if r.Allocator() != nil {
						tmp = r.AcquireString(b)
					} else if len(b) == 0 {
						tmp = ""
					} else {
						tmp = unsafe.String(&b[0], len(b))
					}
				}
				v.Note = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Names) >= n {
					v.Names = v.Names[:n]
				} else {
					v.Names = gsbm.MakeSlice[string](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				{
					b, err := r.ReadBytes()
					if err != nil {
						return err
					}
					if r.Allocator() != nil {
						v.Names[i] = r.AcquireString(b)
					} else if len(b) == 0 {
						v.Names[i] = ""
					} else {
						v.Names[i] = unsafe.String(&b[0], len(b))
					}
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 2
		case 4:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Labels) >= n {
					v.Labels = v.Labels[:n]
				} else {
					v.Labels = gsbm.MakeSlice[Label](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				var u string
				{
					b, err := r.ReadBytes()
					if err != nil {
						return err
					}
					if r.Allocator() != nil {
						u = r.AcquireString(b)
					} else if len(b) == 0 {
						u = ""
					} else {
						u = unsafe.String(&b[0], len(b))
					}
				}
				v.Labels[i] = Label(u)
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 3
		case 5:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.Tags == nil {
				v.Tags = gsbm.MakeMap[string, string](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					b, err := r.ReadBytes()
					if err != nil {
						return err
					}
					if r.Allocator() != nil {
						k = r.AcquireString(b)
					} else if len(b) == 0 {
						k = ""
					} else {
						k = unsafe.String(&b[0], len(b))
					}
				}
				var vv string
				{
					b, err := r.ReadBytes()
					if err != nil {
						return err
					}
					if r.Allocator() != nil {
						vv = r.AcquireString(b)
					} else if len(b) == 0 {
						vv = ""
					} else {
						vv = unsafe.String(&b[0], len(b))
					}
				}
				v.Tags[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 4
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *BorrowRecord) Reset() {
	v.ID = ""
	v.Note = nil
	clear(v.Names)
	v.Names = v.Names[:0]
	clear(v.Labels)
	v.Labels = v.Labels[:0]
	clear(v.Tags)
	gsbm.ClearPresence(v)
}

func (v *BorrowRecord) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
