// Code generated by gsbmcodegen. DO NOT EDIT.

package borrowstrings

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"sort"
)

func (v *PlainRecord) SizeGSBM() int {
	n := 0
	// tag 1 ID
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.ID)
	// tag 2 Note
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	{
		body := 1
		switch {
		case v.Note == nil:
		case *v.Note == "":
		default:
			body += gsbm.SizeString(*v.Note)
		}
		n += gsbm.SizeLengthDelim(body)
	}
	// tag 3 Names
	n += gsbm.SizeTag(3, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Names)))
		for i := range v.Names {
			body_1 += gsbm.SizeString(v.Names[i])
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 4 Labels
	n += gsbm.SizeTag(4, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Labels)))
		for i := range v.Labels {
			body_1 += gsbm.SizeString((string)(v.Labels[i]))
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 5 Tags
	n += gsbm.SizeTag(5, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Tags)))
		for k, vv := range v.Tags {
			body_1 += gsbm.SizeString(k)
			body_1 += gsbm.SizeString(vv)
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	return n
}

func (v *PlainRecord) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Note
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		switch {
		case v.Note == nil:
			w.WritePresenceNil()
		case *v.Note == "":
			w.WritePresenceZero()
		default:
			w.WritePresenceNonZero()
			w.WriteString(*v.Note)
		}
		w.EndLengthDelim(m)
	}
	// tag 3 Names
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Names)))
		for i := range v.Names {
			body_1 += gsbm.SizeString(v.Names[i])
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.Names)))
		for i := range v.Names {
			w.WriteString(v.Names[i])
		}
	}
	// tag 4 Labels
	w.WriteTag(4, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Labels)))
		for i := range v.Labels {
			body_1 += gsbm.SizeString((string)(v.Labels[i]))
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.Labels)))
		for i := range v.Labels {
			w.WriteString((string)(v.Labels[i]))
		}
	}
	// tag 5 Tags
	w.WriteTag(5, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Tags)))
		for k, vv := range v.Tags {
			body_1 += gsbm.SizeString(k)
			body_1 += gsbm.SizeString(vv)
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.Tags)))
		keys := make([]string, 0, len(v.Tags))
		for k := range v.Tags {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.Tags[k]
			w.WriteString(k)
			w.WriteString(vv)
		}
	}
	return w.Err()
}

func (v *PlainRecord) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(true)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.Note = nil
			case gsbm.PresenceZero:
				var z string
				v.Note = &z
			case gsbm.PresenceNonZero:
				var tmp string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					tmp = x
				}
				v.Note = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Names) >= n {
					v.Names = v.Names[:n]
				} else {
					v.Names = gsbm.MakeSlice[string](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					v.Names[i] = x
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 2
		case 4:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Labels) >= n {
					v.Labels = v.Labels[:n]
				} else {
					v.Labels = gsbm.MakeSlice[Label](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				var u string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					u = x
				}
				v.Labels[i] = Label(u)
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 3
		case 5:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.Tags == nil {
				v.Tags = gsbm.MakeMap[string, string](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					vv = x
				}
				v.Tags[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 4
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *PlainRecord) Reset() {
	v.ID = ""
	v.Note = nil
	v.Names = v.Names[:0]
	v.Labels = v.Labels[:0]
	clear(v.Tags)
	gsbm.ClearPresence(v)
}

func (v *PlainRecord) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
