// Code generated by gsbmcodegen. DO NOT EDIT.

package trackpresence

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Offer) SizeGSBM() int {
	var n int
	// tag 1 ID
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.ID)
	// tag 2 Quantity
	n += gsbm.SizeTag(2, gsbm.WireVarint)
	n += gsbm.SizeVarint(int64(v.Quantity))
	// tag 3 Price
	n += gsbm.SizeTag(3, gsbm.WireFixed64)
	n += gsbm.SizeFixed64()
	// tag 4 Active
	n += gsbm.SizeTag(4, gsbm.WireVarint)
	n += gsbm.SizeBool()
	// tag 5 Note
	n += gsbm.SizeTag(5, gsbm.WireLengthDelim)
	if v.Note == nil || *v.Note == "" {
		n += gsbm.SizeLengthDelim(1)
	} else {
		n += gsbm.SizeLengthDelim(1 + gsbm.SizeString(*v.Note))
	}
	return n
}

func (v *Offer) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Quantity
	w.WriteTag(2, gsbm.WireVarint)
	w.WriteVarint(int64(v.Quantity))
	// tag 3 Price
	w.WriteTag(3, gsbm.WireFixed64)
	w.WriteFloat64(v.Price)
	// tag 4 Active
	w.WriteTag(4, gsbm.WireVarint)
	w.WriteBool(v.Active)
	// tag 5 Note
	w.WriteTag(5, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		switch {
		case v.Note == nil:
			w.WritePresenceNil()
		case *v.Note == "":
			w.WritePresenceZero()
		default:
			w.WritePresenceNonZero()
			w.WriteString(*v.Note)
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Offer) UnmarshalGSBM(r *gsbm.Reader) error {
	v.gsbmPresent = [1]uint64{}
	present := &v.gsbmPresent
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Quantity = int64(x)
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireFixed64 {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadFloat64()
				if err != nil {
					return err
				}
				v.Price = x
			}
			present[0] |= 1 << 2
		case 4:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Active = x
			}
			present[0] |= 1 << 3
		case 5:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(true)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.Note = nil
			case gsbm.PresenceZero:
				var z string
				v.Note = &z
			case gsbm.PresenceNonZero:
				var tmp string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					tmp = x
				}
				v.Note = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 4
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Offer) Reset() {
	v.ID = ""
	v.Quantity = 0
	v.Price = 0
	v.Active = false
	v.Note = nil
	v.gsbmPresent = [1]uint64{}
}

func (v *Offer) FieldPresent(tag uint32) bool {
	if tag == 0 || tag > 64 {
		return false
	}
	idx := (tag - 1) >> 6
	bit := (tag - 1) & 63
	return v.gsbmPresent[idx]&(1<<bit) != 0
}
