// Code generated by gsbmcodegen (arena mode). DO NOT EDIT.

package trackpresence

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"go.flaticols.dev/gsbm/storage/gsbmarena"
)

// DecodeOffer decodes data into a *Offer allocated from a. The returned
// value and every string/slice acquired via the Reader's allocator
// (Acquire*/SetAllocator path) are invalidated by a.Release: the
// returned *Offer itself, plus any string/slice header it contains,
// become unsafe to read after Release.
//
// Sub-trees produced by codecs that bypass the allocator have
// heap-backed referents whose own memory outlives Release, but their
// headers still live inside the arena-decoded struct and must be
// copied out before Release to be read afterwards. encoding/json
// output (e.g. via builtins.DecodeJSONBytes) is heap-owned in its
// referents; bytes read via r.ReadBytes alias the source buffer
// passed to NewReader, so their referent's lifetime is bounded by
// the source buffer (which the caller owns), not by the arena. In
// both cases, accessing the field through the arena-decoded value
// after a.Release is use-after-release; detach (copy out) before
// Release to outlive it.
//
// The wire format is identical to heap mode.
func DecodeOffer(data []byte, a *gsbmarena.Arena) (*Offer, error) {
	v := gsbmarena.AllocStruct[Offer](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if _, _, _, err := r.ReadHeader(); err != nil {
		return nil, err
	}
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DecodeOfferBody is the headerless variant: data is the raw root body
// without the 12-byte blob header.
func DecodeOfferBody(data []byte, a *gsbmarena.Arena) (*Offer, error) {
	v := gsbmarena.AllocStruct[Offer](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DetachOffer returns a heap-allocated *Offer with no references into any
// arena. Implemented as a re-encode + heap decode round-trip so the
// heap-mode unmarshal body is the single source of truth.
func DetachOffer(o *Offer) (*Offer, error) {
	w := gsbm.NewWriter(nil)
	if err := o.MarshalGSBM(w); err != nil {
		return nil, err
	}
	if err := w.Err(); err != nil {
		return nil, err
	}
	dst := &Offer{}
	if err := gsbm.DecodeBodyInto(w.Bytes(), dst); err != nil {
		return nil, err
	}
	return dst, nil
}
