// Code generated by gsbmcodegen. DO NOT EDIT.

package nestedcomp

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"sort"
)

func (v *Index) SizeGSBM() int {
	n := 0
	// tag 1 IDsByGroup
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.IDsByGroup)))
		for k, vv := range v.IDsByGroup {
			body_1 += gsbm.SizeString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for i_1 := range vv {
					body_2 += gsbm.SizeString(vv[i_1])
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 2 LabelsByGroup
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.LabelsByGroup)))
		for k, vv := range v.LabelsByGroup {
			body_1 += gsbm.SizeString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for k_1, vv_1 := range vv {
					body_2 += gsbm.SizeString(k_1)
					body_2 += gsbm.SizeString(vv_1)
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 3 MetadataVariants
	n += gsbm.SizeTag(3, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.MetadataVariants)))
		for i := range v.MetadataVariants {
			{
				body_2 := gsbm.SizeUvarint(uint64(len(v.MetadataVariants[i])))
				for k_1, vv_1 := range v.MetadataVariants[i] {
					body_2 += gsbm.SizeString(k_1)
					body_2 += gsbm.SizeString(vv_1)
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 4 Deep
	n += gsbm.SizeTag(4, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Deep)))
		for k, vv := range v.Deep {
			body_1 += gsbm.SizeString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for i_1 := range vv {
					{
						body_3 := gsbm.SizeUvarint(uint64(len(vv[i_1])))
						for k_2, vv_2 := range vv[i_1] {
							body_3 += gsbm.SizeString(k_2)
							body_3 += gsbm.SizeVarint(int64(vv_2))
						}
						body_2 += gsbm.SizeLengthDelim(body_3)
					}
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	return n
}

func (v *Index) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 IDsByGroup
	w.WriteTag(1, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.IDsByGroup)))
		for k, vv := range v.IDsByGroup {
			body_1 += gsbm.SizeString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for i_1 := range vv {
					body_2 += gsbm.SizeString(vv[i_1])
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.IDsByGroup)))
		keys := make([]string, 0, len(v.IDsByGroup))
		for k := range v.IDsByGroup {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.IDsByGroup[k]
			w.WriteString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for i_1 := range vv {
					body_2 += gsbm.SizeString(vv[i_1])
				}
				w.WriteLength(body_2)
				w.WriteUvarint(uint64(len(vv)))
				for i_1 := range vv {
					w.WriteString(vv[i_1])
				}
			}
		}
	}
	// tag 2 LabelsByGroup
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.LabelsByGroup)))
		for k, vv := range v.LabelsByGroup {
			body_1 += gsbm.SizeString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for k_1, vv_1 := range vv {
					body_2 += gsbm.SizeString(k_1)
					body_2 += gsbm.SizeString(vv_1)
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.LabelsByGroup)))
		keys := make([]string, 0, len(v.LabelsByGroup))
		for k := range v.LabelsByGroup {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.LabelsByGroup[k]
			w.WriteString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for k_1, vv_1 := range vv {
					body_2 += gsbm.SizeString(k_1)
					body_2 += gsbm.SizeString(vv_1)
				}
				w.WriteLength(body_2)
				w.WriteUvarint(uint64(len(vv)))
				keys_1 := make([]string, 0, len(vv))
				for k_1 := range vv {
					keys_1 = append(keys_1, k_1)
				}
				sort.Strings(keys_1)
				for _, k_1 := range keys_1 {
					vv_1 := vv[k_1]
					w.WriteString(k_1)
					w.WriteString(vv_1)
				}
			}
		}
	}
	// tag 3 MetadataVariants
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.MetadataVariants)))
		for i := range v.MetadataVariants {
			{
				body_2 := gsbm.SizeUvarint(uint64(len(v.MetadataVariants[i])))
				for k_1, vv_1 := range v.MetadataVariants[i] {
					body_2 += gsbm.SizeString(k_1)
					body_2 += gsbm.SizeString(vv_1)
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.MetadataVariants)))
		for i := range v.MetadataVariants {
			{
				body_2 := gsbm.SizeUvarint(uint64(len(v.MetadataVariants[i])))
				for k_1, vv_1 := range v.MetadataVariants[i] {
					body_2 += gsbm.SizeString(k_1)
					body_2 += gsbm.SizeString(vv_1)
				}
				w.WriteLength(body_2)
				w.WriteUvarint(uint64(len(v.MetadataVariants[i])))
				keys_1 := make([]string, 0, len(v.MetadataVariants[i]))
				for k_1 := range v.MetadataVariants[i] {
					keys_1 = append(keys_1, k_1)
				}
				sort.Strings(keys_1)
				for _, k_1 := range keys_1 {
					vv_1 := v.MetadataVariants[i][k_1]
					w.WriteString(k_1)
					w.WriteString(vv_1)
				}
			}
		}
	}
	// tag 4 Deep
	w.WriteTag(4, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Deep)))
		for k, vv := range v.Deep {
			body_1 += gsbm.SizeString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for i_1 := range vv {
					{
						body_3 := gsbm.SizeUvarint(uint64(len(vv[i_1])))
						for k_2, vv_2 := range vv[i_1] {
							body_3 += gsbm.SizeString(k_2)
							body_3 += gsbm.SizeVarint(int64(vv_2))
						}
						body_2 += gsbm.SizeLengthDelim(body_3)
					}
				}
				body_1 += gsbm.SizeLengthDelim(body_2)
			}
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.Deep)))
		keys := make([]string, 0, len(v.Deep))
		for k := range v.Deep {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.Deep[k]
			w.WriteString(k)
			{
				body_2 := gsbm.SizeUvarint(uint64(len(vv)))
				for i_1 := range vv {
					{
						body_3 := gsbm.SizeUvarint(uint64(len(vv[i_1])))
						for k_2, vv_2 := range vv[i_1] {
							body_3 += gsbm.SizeString(k_2)
							body_3 += gsbm.SizeVarint(int64(vv_2))
						}
						body_2 += gsbm.SizeLengthDelim(body_3)
					}
				}
				w.WriteLength(body_2)
				w.WriteUvarint(uint64(len(vv)))
				for i_1 := range vv {
					{
						body_3 := gsbm.SizeUvarint(uint64(len(vv[i_1])))
						for k_2, vv_2 := range vv[i_1] {
							body_3 += gsbm.SizeString(k_2)
							body_3 += gsbm.SizeVarint(int64(vv_2))
						}
						w.WriteLength(body_3)
						w.WriteUvarint(uint64(len(vv[i_1])))
						keys_2 := make([]string, 0, len(vv[i_1]))
						for k_2 := range vv[i_1] {
							keys_2 = append(keys_2, k_2)
						}
						sort.Strings(keys_2)
						for _, k_2 := range keys_2 {
							vv_2 := vv[i_1][k_2]
							w.WriteString(k_2)
							w.WriteVarint(int64(vv_2))
						}
					}
				}
			}
		}
	}
	return w.Err()
}

func (v *Index) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.IDsByGroup == nil {
				v.IDsByGroup = gsbm.MakeMap[string, []string](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv []string
				saved_1, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				n_1, err := r.ReadLength()
				if err != nil {
					return err
				}
				if n_1 > 0 {
					if cap(vv) >= n_1 {
						vv = vv[:n_1]
					} else {
						vv = gsbm.MakeSlice[string](r, n_1)
					}
					if err := r.Err(); err != nil {
						return err
					}
				}
				for i_1 := 0; i_1 < n_1; i_1++ {
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						vv[i_1] = x
					}
				}
				if err := r.EndLengthDelim(saved_1); err != nil {
					return err
				}
				v.IDsByGroup[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.LabelsByGroup == nil {
				v.LabelsByGroup = gsbm.MakeMap[string, map[string]string](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv map[string]string
				saved_1, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				n_1, err := r.ReadLength()
				if err != nil {
					return err
				}
				if n_1 > 0 && vv == nil {
					vv = gsbm.MakeMap[string, string](r, n_1)
				}
				for i_1 := 0; i_1 < n_1; i_1++ {
					var k_1 string
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						k_1 = x
					}
					var vv_1 string
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						vv_1 = x
					}
					vv[k_1] = vv_1
				}
				if err := r.EndLengthDelim(saved_1); err != nil {
					return err
				}
				v.LabelsByGroup[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.MetadataVariants) >= n {
					v.MetadataVariants = v.MetadataVariants[:n]
				} else {
					v.MetadataVariants = gsbm.MakeSlice[map[string]string](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				clear(v.MetadataVariants[i])
				saved_1, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				n_1, err := r.ReadLength()
				if err != nil {
					return err
				}
				if n_1 > 0 && v.MetadataVariants[i] == nil {
					v.MetadataVariants[i] = gsbm.MakeMap[string, string](r, n_1)
				}
				for i_1 := 0; i_1 < n_1; i_1++ {
					var k_1 string
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						k_1 = x
					}
					var vv_1 string
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						vv_1 = x
					}
					v.MetadataVariants[i][k_1] = vv_1
				}
				if err := r.EndLengthDelim(saved_1); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 2
		case 4:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.Deep == nil {
				v.Deep = gsbm.MakeMap[string, []map[string]int64](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv []map[string]int64
				saved_1, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				n_1, err := r.ReadLength()
				if err != nil {
					return err
				}
				if n_1 > 0 {
					if cap(vv) >= n_1 {
						vv = vv[:n_1]
					} else {
						vv = gsbm.MakeSlice[map[string]int64](r, n_1)
					}
					if err := r.Err(); err != nil {
						return err
					}
				}
				for i_1 := 0; i_1 < n_1; i_1++ {
					clear(vv[i_1])
					saved_2, err := r.BeginLengthDelim()
					if err != nil {
						return err
					}
					n_2, err := r.ReadLength()
					if err != nil {
						return err
					}
					if n_2 > 0 && vv[i_1] == nil {
						vv[i_1] = gsbm.MakeMap[string, int64](r, n_2)
					}
					for i_2 := 0; i_2 < n_2; i_2++ {
						var k_2 string
						{
							x, err := r.ReadString()
							if err != nil {
								return err
							}
							k_2 = x
						}
						var vv_2 int64
						{
							x, err := r.ReadVarint()
							if err != nil {
								return err
							}
							vv_2 = int64(x)
						}
						vv[i_1][k_2] = vv_2
					}
					if err := r.EndLengthDelim(saved_2); err != nil {
						return err
					}
				}
				if err := r.EndLengthDelim(saved_1); err != nil {
					return err
				}
				v.Deep[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 3
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Index) Reset() {
	clear(v.IDsByGroup)
	clear(v.LabelsByGroup)
	clear(v.MetadataVariants)
	v.MetadataVariants = v.MetadataVariants[:0]
	clear(v.Deep)
	gsbm.ClearPresence(v)
}

func (v *Index) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
