// Code generated by odmcodegen. DO NOT EDIT.

package sample

import (
	"github.com/flaticols/gsbm/storage/odm"
)

func (v *Customer) MarshalODM(w *odm.Writer) error {
	// tag 1 Name
	w.WriteTag(1, odm.WireLengthDelim)
	w.WriteString(v.Name)
	// tag 2 Email
	w.WriteTag(2, odm.WireLengthDelim)
	w.WriteString(v.Email)
	return w.Err()
}

func (v *Customer) UnmarshalODM(r *odm.Reader) error {
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Name = x
			}
		case 2:
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Email = x
			}
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Customer) Reset() {
	v.Name = ""
	v.Email = ""
}
