// Code generated by odmcodegen. DO NOT EDIT.

package sample

import (
	"github.com/flaticols/gsbm/storage/odm"
)

func (v *Item) MarshalODM(w *odm.Writer) error {
	// tag 1 SKU
	w.WriteTag(1, odm.WireLengthDelim)
	w.WriteString(v.SKU)
	// tag 2 Count
	w.WriteTag(2, odm.WireVarint)
	w.WriteVarint(int64(v.Count))
	return w.Err()
}

func (v *Item) UnmarshalODM(r *odm.Reader) error {
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.SKU = x
			}
		case 2:
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Count = int64(x)
			}
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Item) Reset() {
	v.SKU = ""
	v.Count = 0
}
