// Code generated by odmcodegen. DO NOT EDIT.

package sample

import (
	"github.com/flaticols/gsbm/storage/odm"
)

func (v *Order) MarshalODM(w *odm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, odm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Quantity
	w.WriteTag(2, odm.WireVarint)
	w.WriteVarint(int64(v.Quantity))
	// tag 3 Price
	w.WriteTag(3, odm.WireFixed64)
	w.WriteFloat64(v.Price)
	// tag 4 Active
	w.WriteTag(4, odm.WireVarint)
	w.WriteBool(v.Active)
	// tag 5 Note
	w.WriteTag(5, odm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		switch {
		case v.Note == nil:
			w.WritePresenceNil()
		case *v.Note == "":
			w.WritePresenceZero()
		default:
			w.WritePresenceNonZero()
			w.WriteString(*v.Note)
		}
		w.EndLengthDelim(m)
	}
	// tag 6 Customer
	w.WriteTag(6, odm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if v.Customer == nil {
			w.WritePresenceNil()
		} else {
			w.WritePresenceNonZero()
			if err := v.Customer.MarshalODM(w); err != nil {
				return err
			}
		}
		w.EndLengthDelim(m)
	}
	// tag 7 Items
	w.WriteTag(7, odm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			inner := w.BeginLengthDelim()
			if err := v.Items[i].MarshalODM(w); err != nil {
				return err
			}
			w.EndLengthDelim(inner)
		}
		w.EndLengthDelim(m)
	}
	// tag 8 Tags
	w.WriteTag(8, odm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Tags)))
		for k, vv := range v.Tags {
			w.WriteString(k)
			w.WriteVarint(int64(vv))
		}
		w.EndLengthDelim(m)
	}
	// tag 9 Payload
	w.WriteTag(9, odm.WireLengthDelim)
	w.WriteBytes(v.Payload)
	// tag 10 Total
	w.WriteTag(10, odm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		if err := v.Total.MarshalODM(w); err != nil {
			return err
		}
		w.EndLengthDelim(m)
	}
	// tag 11 Counts
	w.WriteTag(11, odm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Counts)))
		for i := range v.Counts {
			w.WriteVarint(int64(v.Counts[i]))
		}
		w.EndLengthDelim(m)
	}
	// tag 12 Aliases
	w.WriteTag(12, odm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Aliases)))
		for k, vv := range v.Aliases {
			w.WriteString(k)
			w.WriteString((string)(vv))
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Order) UnmarshalODM(r *odm.Reader) error {
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
		case 2:
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Quantity = int64(x)
			}
		case 3:
			{
				x, err := r.ReadFloat64()
				if err != nil {
					return err
				}
				v.Price = x
			}
		case 4:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Active = x
			}
		case 5:
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(true)
			if err != nil {
				return err
			}
			switch state {
			case odm.PresenceNil:
				v.Note = nil
			case odm.PresenceZero:
				z := ""
				v.Note = &z
			case odm.PresenceNonZero:
				var tmp string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					tmp = x
				}
				v.Note = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
		case 6:
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(false)
			if err != nil {
				return err
			}
			switch state {
			case odm.PresenceNil:
				v.Customer = nil
			case odm.PresenceNonZero:
				v.Customer = &Customer{}
				if err := v.Customer.UnmarshalODM(r); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
		case 7:
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Items) >= n {
					v.Items = v.Items[:n]
				} else {
					v.Items = make([]Item, n)
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.Items[i] = Item{}
				if err := v.Items[i].UnmarshalODM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
		case 8:
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.Tags == nil {
				v.Tags = make(map[string]int64, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					vv = int64(x)
				}
				v.Tags[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
		case 9:
			b, err := r.ReadBytes()
			if err != nil {
				return err
			}
			v.Payload = append(v.Payload[:0], b...)
		case 10:
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			if err := v.Total.UnmarshalODM(r); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
		case 11:
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Counts) >= n {
					v.Counts = v.Counts[:n]
				} else {
					v.Counts = make([]int64, n)
				}
			}
			for i := 0; i < n; i++ {
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					v.Counts[i] = int64(x)
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
		case 12:
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.Aliases == nil {
				v.Aliases = make(map[string]Label, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv Label
				{
					var tmp string
					{
						x, err := r.ReadString()
						if err != nil {
							return err
						}
						tmp = x
					}
					vv = Label(tmp)
				}
				v.Aliases[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}
