// Code generated by odmcodegen (arena mode). DO NOT EDIT.

package sample

import (
	"github.com/flaticols/gsbm/storage/odm"
	"github.com/flaticols/gsbm/storage/odmarena"
)

// DecodeOrder decodes data into a *Order allocated from a. The returned
// value, and every string/slice it transitively references, are
// invalidated by a.Release. The wire format is identical to heap mode.
func DecodeOrder(data []byte, a *odmarena.Arena) (*Order, error) {
	v := odmarena.AllocStruct[Order](a)
	v.Reset()
	r := odm.NewReader(data)
	r.SetAllocator(a)
	if _, _, err := r.ReadHeader(); err != nil {
		return nil, err
	}
	if err := v.UnmarshalODM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DecodeOrderBody is the headerless variant: data is the raw root body
// without the 8-byte blob header.
func DecodeOrderBody(data []byte, a *odmarena.Arena) (*Order, error) {
	v := odmarena.AllocStruct[Order](a)
	v.Reset()
	r := odm.NewReader(data)
	r.SetAllocator(a)
	if err := v.UnmarshalODM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DetachOrder returns a heap-allocated *Order with no references into any
// arena. Implemented as a re-encode + heap decode round-trip so the
// heap-mode unmarshal body is the single source of truth.
func DetachOrder(o *Order) (*Order, error) {
	w := odm.NewWriter(nil)
	if err := o.MarshalODM(w); err != nil {
		return nil, err
	}
	if err := w.Err(); err != nil {
		return nil, err
	}
	dst := &Order{}
	if err := odm.DecodeBodyInto(w.Bytes(), dst); err != nil {
		return nil, err
	}
	return dst, nil
}
