// Code generated by odmcodegen. DO NOT EDIT.

package sample

import (
	"github.com/flaticols/gsbm/storage/odm"
)

func (v *Total) MarshalODM(w *odm.Writer) error {
	// tag 1 Currency
	w.WriteTag(1, odm.WireLengthDelim)
	w.WriteString(v.Currency)
	// tag 2 Amount
	w.WriteTag(2, odm.WireFixed64)
	w.WriteFloat64(v.Amount)
	return w.Err()
}

func (v *Total) UnmarshalODM(r *odm.Reader) error {
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Currency = x
			}
		case 2:
			{
				x, err := r.ReadFloat64()
				if err != nil {
					return err
				}
				v.Amount = x
			}
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Total) Reset() {
	v.Currency = ""
	v.Amount = 0
}
