// Code generated by gsbmcodegen. DO NOT EDIT.

package embed

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Deep) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Total
	w.WriteTag(1, gsbm.WireVarint)
	w.WriteVarint(int64(v.Mid.Base.Total))
	// tag 3 Note
	w.WriteTag(3, gsbm.WireLengthDelim)
	w.WriteString(v.Mid.Note)
	// tag 4 Caller
	w.WriteTag(4, gsbm.WireLengthDelim)
	w.WriteString(v.Caller)
	return w.Err()
}

func (v *Deep) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Mid.Base.Total = int64(x)
			}
			gsbm.MarkPresent(v, 1)
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Mid.Note = x
			}
			gsbm.MarkPresent(v, 3)
		case 4:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Caller = x
			}
			gsbm.MarkPresent(v, 4)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Deep) Reset() {
	v.Mid.Base.Total = 0
	v.Mid.Note = ""
	v.Caller = ""
	gsbm.ClearPresence(v)
}

func (v *Deep) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
