// Code generated by gsbmcodegen. DO NOT EDIT.

package embed

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *DoublePtr) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *DoublePtr) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Total
	if v.PtrMid != nil && v.PtrMid.Base != nil {
		w.WriteTag(1, gsbm.WireVarint)
		w.WriteVarint(int64(v.PtrMid.Base.Total))
	}
	// tag 7 Caller
	w.WriteTag(7, gsbm.WireLengthDelim)
	w.WriteString(v.Caller)
	return w.Err()
}

func (v *DoublePtr) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			if v.PtrMid == nil {
				v.PtrMid = &PtrMid{}
			}
			if v.PtrMid.Base == nil {
				v.PtrMid.Base = &Base{}
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.PtrMid.Base.Total = int64(x)
			}
			present[0] |= 1 << 0
		case 7:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Caller = x
			}
			present[0] |= 1 << 6
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *DoublePtr) Reset() {
	v.PtrMid = nil
	v.Caller = ""
	gsbm.ClearPresence(v)
}

func (v *DoublePtr) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
