// Code generated by gsbmcodegen (arena mode). DO NOT EDIT.

package embed

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"go.flaticols.dev/gsbm/storage/gsbmarena"
)

// DecodeExtended decodes data into a *Extended allocated from a. The returned
// value, and every string/slice it transitively references, are
// invalidated by a.Release. The wire format is identical to heap mode.
func DecodeExtended(data []byte, a *gsbmarena.Arena) (*Extended, error) {
	v := gsbmarena.AllocStruct[Extended](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if _, _, err := r.ReadHeader(); err != nil {
		return nil, err
	}
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DecodeExtendedBody is the headerless variant: data is the raw root body
// without the 8-byte blob header.
func DecodeExtendedBody(data []byte, a *gsbmarena.Arena) (*Extended, error) {
	v := gsbmarena.AllocStruct[Extended](a)
	v.Reset()
	r := gsbm.NewReader(data)
	r.SetAllocator(a)
	if err := v.UnmarshalGSBM(r); err != nil {
		return nil, err
	}
	if err := r.Err(); err != nil {
		return nil, err
	}
	return v, nil
}

// DetachExtended returns a heap-allocated *Extended with no references into any
// arena. Implemented as a re-encode + heap decode round-trip so the
// heap-mode unmarshal body is the single source of truth.
func DetachExtended(o *Extended) (*Extended, error) {
	w := gsbm.NewWriter(nil)
	if err := o.MarshalGSBM(w); err != nil {
		return nil, err
	}
	if err := w.Err(); err != nil {
		return nil, err
	}
	dst := &Extended{}
	if err := gsbm.DecodeBodyInto(w.Bytes(), dst); err != nil {
		return nil, err
	}
	return dst, nil
}
