// Code generated by gsbmcodegen. DO NOT EDIT.

package embed

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Flat) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *Flat) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Total
	w.WriteTag(1, gsbm.WireVarint)
	w.WriteVarint(int64(v.Total))
	// tag 2 Reason
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.Reason)
	return w.Err()
}

func (v *Flat) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Total = int64(x)
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Reason = x
			}
			present[0] |= 1 << 1
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Flat) Reset() {
	v.Total = 0
	v.Reason = ""
	gsbm.ClearPresence(v)
}

func (v *Flat) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
