// Code generated by gsbmcodegen. DO NOT EDIT.

package embed

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *PtrExtended) SizeGSBM() int {
	var n int
	// tag 1 Total
	if v.Base != nil {
		n += gsbm.SizeTag(1, gsbm.WireVarint)
		n += gsbm.SizeVarint(int64(v.Base.Total))
	}
	// tag 2 Reason
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Reason)
	return n
}

func (v *PtrExtended) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Total
	if v.Base != nil {
		w.WriteTag(1, gsbm.WireVarint)
		w.WriteVarint(int64(v.Base.Total))
	}
	// tag 2 Reason
	w.WriteTag(2, gsbm.WireLengthDelim)
	w.WriteString(v.Reason)
	return w.Err()
}

func (v *PtrExtended) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			if v.Base == nil {
				v.Base = &Base{}
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.Base.Total = int64(x)
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Reason = x
			}
			gsbm.MarkPresent(v, 2)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *PtrExtended) Reset() {
	v.Base = nil
	v.Reason = ""
	gsbm.ClearPresence(v)
}

func (v *PtrExtended) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
