// Code generated by gsbmcodegen. DO NOT EDIT.

package embed

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *WrappedPtr) SizeGSBM() int {
	var n int
	// tag 1 Total
	if v.PtrCarrier.Base != nil {
		n += gsbm.SizeTag(1, gsbm.WireVarint)
		n += gsbm.SizeVarint(int64(v.PtrCarrier.Base.Total))
	}
	// tag 5 Note
	n += gsbm.SizeTag(5, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.PtrCarrier.Note)
	// tag 6 Caller
	n += gsbm.SizeTag(6, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Caller)
	return n
}

func (v *WrappedPtr) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Total
	if v.PtrCarrier.Base != nil {
		w.WriteTag(1, gsbm.WireVarint)
		w.WriteVarint(int64(v.PtrCarrier.Base.Total))
	}
	// tag 5 Note
	w.WriteTag(5, gsbm.WireLengthDelim)
	w.WriteString(v.PtrCarrier.Note)
	// tag 6 Caller
	w.WriteTag(6, gsbm.WireLengthDelim)
	w.WriteString(v.Caller)
	return w.Err()
}

func (v *WrappedPtr) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			if v.PtrCarrier.Base == nil {
				v.PtrCarrier.Base = &Base{}
			}
			{
				x, err := r.ReadVarint()
				if err != nil {
					return err
				}
				v.PtrCarrier.Base.Total = int64(x)
			}
			present[0] |= 1 << 0
		case 5:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.PtrCarrier.Note = x
			}
			present[0] |= 1 << 4
		case 6:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Caller = x
			}
			present[0] |= 1 << 5
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *WrappedPtr) Reset() {
	v.PtrCarrier.Base = nil
	v.PtrCarrier.Note = ""
	v.Caller = ""
	gsbm.ClearPresence(v)
}

func (v *WrappedPtr) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
