// Code generated by gsbmcodegen. DO NOT EDIT.

package graph

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
	"sort"
)

func (v *Catalog) SizeGSBM() int {
	n := 0
	// tag 1 ID
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.ID)
	// tag 2 Sections
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Sections)))
		for i := range v.Sections {
			body_1 += gsbm.SizeLengthDelim(v.Sections[i].SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 3 Tags
	n += gsbm.SizeTag(3, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Tags)))
		for k, vv := range v.Tags {
			body_1 += gsbm.SizeString(k)
			body_1 += gsbm.SizeLengthDelim(vv.SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body_1)
	}
	// tag 536870911 Tail
	n += gsbm.SizeTag(536870911, gsbm.WireLengthDelim)
	n += gsbm.SizeLengthDelim(v.Tail.SizeGSBM())
	return n
}

func (v *Catalog) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 ID
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.ID)
	// tag 2 Sections
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Sections)))
		for i := range v.Sections {
			body_1 += gsbm.SizeLengthDelim(v.Sections[i].SizeGSBM())
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.Sections)))
		for i := range v.Sections {
			w.WriteLength(v.Sections[i].SizeGSBM())
			if err := v.Sections[i].MarshalGSBM(w); err != nil {
				return err
			}
		}
	}
	// tag 3 Tags
	w.WriteTag(3, gsbm.WireLengthDelim)
	{
		body_1 := gsbm.SizeUvarint(uint64(len(v.Tags)))
		for k, vv := range v.Tags {
			body_1 += gsbm.SizeString(k)
			body_1 += gsbm.SizeLengthDelim(vv.SizeGSBM())
		}
		w.WriteLength(body_1)
		w.WriteUvarint(uint64(len(v.Tags)))
		keys := make([]string, 0, len(v.Tags))
		for k := range v.Tags {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			vv := v.Tags[k]
			w.WriteString(k)
			w.WriteLength(vv.SizeGSBM())
			if err := vv.MarshalGSBM(w); err != nil {
				return err
			}
		}
	}
	// tag 536870911 Tail
	w.WriteTag(536870911, gsbm.WireLengthDelim)
	w.WriteLength(v.Tail.SizeGSBM())
	if err := v.Tail.MarshalGSBM(w); err != nil {
		return err
	}
	return w.Err()
}

func (v *Catalog) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.ID = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Sections) >= n {
					v.Sections = v.Sections[:n]
				} else {
					v.Sections = gsbm.MakeSlice[Section](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.Sections[i].Reset()
				if err := v.Sections[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 1
		case 3:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 && v.Tags == nil {
				v.Tags = gsbm.MakeMap[string, Tag](r, n)
			}
			for i := 0; i < n; i++ {
				var k string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					k = x
				}
				var vv Tag
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				if err := vv.UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
				v.Tags[k] = vv
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 2
		case 536870911:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			if err := v.Tail.UnmarshalGSBM(r); err != nil {
				return err
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Catalog) Reset() {
	v.ID = ""
	for i := range v.Sections {
		v.Sections[i].Reset()
	}
	v.Sections = v.Sections[:0]
	clear(v.Tags)
	v.Tail.Reset()
	gsbm.ClearPresence(v)
}

func (v *Catalog) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
