// Code generated by gsbmcodegen. DO NOT EDIT.

package graph

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *EdgeMarker) SizeGSBM() int {
	cw := gsbm.NewCountingWriter()
	_ = v.MarshalGSBM(cw)
	return cw.Size()
}

func (v *EdgeMarker) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Marker
	w.WriteTag(1, gsbm.WireVarint)
	w.WriteBool(v.Marker)
	return w.Err()
}

func (v *EdgeMarker) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireVarint {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Marker = x
			}
			present[0] |= 1 << 0
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *EdgeMarker) Reset() {
	v.Marker = false
	gsbm.ClearPresence(v)
}

func (v *EdgeMarker) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
