// Code generated by gsbmcodegen. DO NOT EDIT.

package graph

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Item) SizeGSBM() int {
	var n int
	// tag 1 SKU
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.SKU)
	// tag 2 Note
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	if v.Note == nil || *v.Note == "" {
		n += gsbm.SizeLengthDelim(1)
	} else {
		n += gsbm.SizeLengthDelim(1 + gsbm.SizeString(*v.Note))
	}
	return n
}

func (v *Item) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 SKU
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.SKU)
	// tag 2 Note
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		switch {
		case v.Note == nil:
			w.WritePresenceNil()
		case *v.Note == "":
			w.WritePresenceZero()
		default:
			w.WritePresenceNonZero()
			w.WriteString(*v.Note)
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Item) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.SKU = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(true)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.Note = nil
			case gsbm.PresenceZero:
				var z string
				v.Note = &z
			case gsbm.PresenceNonZero:
				var tmp string
				{
					x, err := r.ReadString()
					if err != nil {
						return err
					}
					tmp = x
				}
				v.Note = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 2)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Item) Reset() {
	v.SKU = ""
	v.Note = nil
	gsbm.ClearPresence(v)
}

func (v *Item) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
