// Code generated by gsbmcodegen. DO NOT EDIT.

package graph

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Section) SizeGSBM() int {
	var n int
	// tag 1 Name
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Name)
	// tag 2 Items
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	{
		body := gsbm.SizeUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			body += gsbm.SizeLengthDelim(v.Items[i].SizeGSBM())
		}
		n += gsbm.SizeLengthDelim(body)
	}
	return n
}

func (v *Section) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Name
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Name)
	// tag 2 Items
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		w.WriteUvarint(uint64(len(v.Items)))
		for i := range v.Items {
			inner := w.BeginLengthDelim()
			if err := v.Items[i].MarshalGSBM(w); err != nil {
				return err
			}
			w.EndLengthDelim(inner)
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Section) UnmarshalGSBM(r *gsbm.Reader) error {
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Name = x
			}
			gsbm.MarkPresent(v, 1)
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			n, err := r.ReadLength()
			if err != nil {
				return err
			}
			if n > 0 {
				if cap(v.Items) >= n {
					v.Items = v.Items[:n]
				} else {
					v.Items = gsbm.MakeSlice[Item](r, n)
				}
				if err := r.Err(); err != nil {
					return err
				}
			}
			for i := 0; i < n; i++ {
				inner, err := r.BeginLengthDelim()
				if err != nil {
					return err
				}
				v.Items[i].Reset()
				if err := v.Items[i].UnmarshalGSBM(r); err != nil {
					return err
				}
				if err := r.EndLengthDelim(inner); err != nil {
					return err
				}
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			gsbm.MarkPresent(v, 2)
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	return r.Err()
}

func (v *Section) Reset() {
	v.Name = ""
	for i := range v.Items {
		v.Items[i].Reset()
	}
	v.Items = v.Items[:0]
	gsbm.ClearPresence(v)
}

func (v *Section) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
