// Code generated by gsbmcodegen. DO NOT EDIT.

package graph

import (
	"go.flaticols.dev/gsbm/storage/gsbm"
)

func (v *Tag) SizeGSBM() int {
	n := 0
	// tag 1 Slug
	n += gsbm.SizeTag(1, gsbm.WireLengthDelim)
	n += gsbm.SizeString(v.Slug)
	// tag 2 Weight
	n += gsbm.SizeTag(2, gsbm.WireLengthDelim)
	{
		body := 1
		switch {
		case v.Weight == nil:
		case *v.Weight == 0:
		default:
			body += gsbm.SizeVarint(int64(*v.Weight))
		}
		n += gsbm.SizeLengthDelim(body)
	}
	return n
}

func (v *Tag) MarshalGSBM(w *gsbm.Writer) error {
	// tag 1 Slug
	w.WriteTag(1, gsbm.WireLengthDelim)
	w.WriteString(v.Slug)
	// tag 2 Weight
	w.WriteTag(2, gsbm.WireLengthDelim)
	{
		m := w.BeginLengthDelim()
		switch {
		case v.Weight == nil:
			w.WritePresenceNil()
		case *v.Weight == 0:
			w.WritePresenceZero()
		default:
			w.WritePresenceNonZero()
			w.WriteVarint(int64(*v.Weight))
		}
		w.EndLengthDelim(m)
	}
	return w.Err()
}

func (v *Tag) UnmarshalGSBM(r *gsbm.Reader) error {
	var present [1]uint64
	gsbm.ClearPresence(v)
	for r.HasMore() {
		tag, wt, err := r.ReadTag()
		if err != nil {
			return err
		}
		switch tag {
		case 1:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			{
				x, err := r.ReadString()
				if err != nil {
					return err
				}
				v.Slug = x
			}
			present[0] |= 1 << 0
		case 2:
			if wt != gsbm.WireLengthDelim {
				return gsbm.ErrWrongWireType
			}
			saved, err := r.BeginLengthDelim()
			if err != nil {
				return err
			}
			state, err := r.ReadPresenceByte(true)
			if err != nil {
				return err
			}
			switch state {
			case gsbm.PresenceNil:
				v.Weight = nil
			case gsbm.PresenceZero:
				var z int64
				v.Weight = &z
			case gsbm.PresenceNonZero:
				var tmp int64
				{
					x, err := r.ReadVarint()
					if err != nil {
						return err
					}
					tmp = int64(x)
				}
				v.Weight = &tmp
			}
			if err := r.EndLengthDelim(saved); err != nil {
				return err
			}
			present[0] |= 1 << 1
		default:
			if err := r.SkipField(wt); err != nil {
				return err
			}
		}
	}
	_ = present
	return r.Err()
}

func (v *Tag) Reset() {
	v.Slug = ""
	v.Weight = nil
	gsbm.ClearPresence(v)
}

func (v *Tag) FieldPresent(tag uint32) bool {
	return gsbm.IsPresent(v, tag)
}
